// Code generated by go-swagger; DO NOT EDIT.

package tools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
	garm_params "github.com/cloudbase/garm/params"
)

// GarmAgentListReader is a Reader for the GarmAgentList structure.
type GarmAgentListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GarmAgentListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGarmAgentListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGarmAgentListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /tools/garm-agent] GarmAgentList", response, response.Code())
	}
}

// NewGarmAgentListOK creates a GarmAgentListOK with default headers values
func NewGarmAgentListOK() *GarmAgentListOK {
	return &GarmAgentListOK{}
}

/*
GarmAgentListOK describes a response with status code 200, with default header values.

GARMAgentToolsPaginatedResponse
*/
type GarmAgentListOK struct {
	Payload garm_params.GARMAgentToolsPaginatedResponse
}

// IsSuccess returns true when this garm agent list o k response has a 2xx status code
func (o *GarmAgentListOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this garm agent list o k response has a 3xx status code
func (o *GarmAgentListOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this garm agent list o k response has a 4xx status code
func (o *GarmAgentListOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this garm agent list o k response has a 5xx status code
func (o *GarmAgentListOK) IsServerError() bool {
	return false
}

// IsCode returns true when this garm agent list o k response a status code equal to that given
func (o *GarmAgentListOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the garm agent list o k response
func (o *GarmAgentListOK) Code() int {
	return 200
}

func (o *GarmAgentListOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tools/garm-agent][%d] garmAgentListOK %s", 200, payload)
}

func (o *GarmAgentListOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tools/garm-agent][%d] garmAgentListOK %s", 200, payload)
}

func (o *GarmAgentListOK) GetPayload() garm_params.GARMAgentToolsPaginatedResponse {
	return o.Payload
}

func (o *GarmAgentListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGarmAgentListBadRequest creates a GarmAgentListBadRequest with default headers values
func NewGarmAgentListBadRequest() *GarmAgentListBadRequest {
	return &GarmAgentListBadRequest{}
}

/*
GarmAgentListBadRequest describes a response with status code 400, with default header values.

APIErrorResponse
*/
type GarmAgentListBadRequest struct {
	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this garm agent list bad request response has a 2xx status code
func (o *GarmAgentListBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this garm agent list bad request response has a 3xx status code
func (o *GarmAgentListBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this garm agent list bad request response has a 4xx status code
func (o *GarmAgentListBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this garm agent list bad request response has a 5xx status code
func (o *GarmAgentListBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this garm agent list bad request response a status code equal to that given
func (o *GarmAgentListBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the garm agent list bad request response
func (o *GarmAgentListBadRequest) Code() int {
	return 400
}

func (o *GarmAgentListBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tools/garm-agent][%d] garmAgentListBadRequest %s", 400, payload)
}

func (o *GarmAgentListBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tools/garm-agent][%d] garmAgentListBadRequest %s", 400, payload)
}

func (o *GarmAgentListBadRequest) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *GarmAgentListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
