// Code generated by go-swagger; DO NOT EDIT.

package tools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
	garm_params "github.com/cloudbase/garm/params"
)

// ListGARMAgentReleasesReader is a Reader for the ListGARMAgentReleases structure.
type ListGARMAgentReleasesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListGARMAgentReleasesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListGARMAgentReleasesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListGARMAgentReleasesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /tools/garm-agent/releases] ListGARMAgentReleases", response, response.Code())
	}
}

// NewListGARMAgentReleasesOK creates a ListGARMAgentReleasesOK with default headers values
func NewListGARMAgentReleasesOK() *ListGARMAgentReleasesOK {
	return &ListGARMAgentReleasesOK{}
}

/*
ListGARMAgentReleasesOK describes a response with status code 200, with default header values.

GARMAgentReleases
*/
type ListGARMAgentReleasesOK struct {
	Payload garm_params.GARMAgentReleases
}

// IsSuccess returns true when this list g a r m agent releases o k response has a 2xx status code
func (o *ListGARMAgentReleasesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list g a r m agent releases o k response has a 3xx status code
func (o *ListGARMAgentReleasesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list g a r m agent releases o k response has a 4xx status code
func (o *ListGARMAgentReleasesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list g a r m agent releases o k response has a 5xx status code
func (o *ListGARMAgentReleasesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list g a r m agent releases o k response a status code equal to that given
func (o *ListGARMAgentReleasesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list g a r m agent releases o k response
func (o *ListGARMAgentReleasesOK) Code() int {
	return 200
}

func (o *ListGARMAgentReleasesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tools/garm-agent/releases][%d] listGARMAgentReleasesOK %s", 200, payload)
}

func (o *ListGARMAgentReleasesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tools/garm-agent/releases][%d] listGARMAgentReleasesOK %s", 200, payload)
}

func (o *ListGARMAgentReleasesOK) GetPayload() garm_params.GARMAgentReleases {
	return o.Payload
}

func (o *ListGARMAgentReleasesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListGARMAgentReleasesBadRequest creates a ListGARMAgentReleasesBadRequest with default headers values
func NewListGARMAgentReleasesBadRequest() *ListGARMAgentReleasesBadRequest {
	return &ListGARMAgentReleasesBadRequest{}
}

/*
ListGARMAgentReleasesBadRequest describes a response with status code 400, with default header values.

APIErrorResponse
*/
type ListGARMAgentReleasesBadRequest struct {
	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this list g a r m agent releases bad request response has a 2xx status code
func (o *ListGARMAgentReleasesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list g a r m agent releases bad request response has a 3xx status code
func (o *ListGARMAgentReleasesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list g a r m agent releases bad request response has a 4xx status code
func (o *ListGARMAgentReleasesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list g a r m agent releases bad request response has a 5xx status code
func (o *ListGARMAgentReleasesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list g a r m agent releases bad request response a status code equal to that given
func (o *ListGARMAgentReleasesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list g a r m agent releases bad request response
func (o *ListGARMAgentReleasesBadRequest) Code() int {
	return 400
}

func (o *ListGARMAgentReleasesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tools/garm-agent/releases][%d] listGARMAgentReleasesBadRequest %s", 400, payload)
}

func (o *ListGARMAgentReleasesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /tools/garm-agent/releases][%d] listGARMAgentReleasesBadRequest %s", 400, payload)
}

func (o *ListGARMAgentReleasesBadRequest) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *ListGARMAgentReleasesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
