// Code generated by go-swagger; DO NOT EDIT.

package scalesets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
	garm_params "github.com/cloudbase/garm/params"
)

// ListScaleSetJobsReader is a Reader for the ListScaleSetJobs structure.
type ListScaleSetJobsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListScaleSetJobsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListScaleSetJobsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListScaleSetJobsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListScaleSetJobsOK creates a ListScaleSetJobsOK with default headers values
func NewListScaleSetJobsOK() *ListScaleSetJobsOK {
	return &ListScaleSetJobsOK{}
}

/*
ListScaleSetJobsOK describes a response with status code 200, with default header values.

ScaleSetJobs
*/
type ListScaleSetJobsOK struct {
	Payload garm_params.ScaleSetJobs
}

// IsSuccess returns true when this list scale set jobs o k response has a 2xx status code
func (o *ListScaleSetJobsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list scale set jobs o k response has a 3xx status code
func (o *ListScaleSetJobsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list scale set jobs o k response has a 4xx status code
func (o *ListScaleSetJobsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list scale set jobs o k response has a 5xx status code
func (o *ListScaleSetJobsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list scale set jobs o k response a status code equal to that given
func (o *ListScaleSetJobsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list scale set jobs o k response
func (o *ListScaleSetJobsOK) Code() int {
	return 200
}

func (o *ListScaleSetJobsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /scalesets/{scalesetID}/jobs][%d] listScaleSetJobsOK %s", 200, payload)
}

func (o *ListScaleSetJobsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /scalesets/{scalesetID}/jobs][%d] listScaleSetJobsOK %s", 200, payload)
}

func (o *ListScaleSetJobsOK) GetPayload() garm_params.ScaleSetJobs {
	return o.Payload
}

func (o *ListScaleSetJobsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListScaleSetJobsDefault creates a ListScaleSetJobsDefault with default headers values
func NewListScaleSetJobsDefault(code int) *ListScaleSetJobsDefault {
	return &ListScaleSetJobsDefault{
		_statusCode: code,
	}
}

/*
ListScaleSetJobsDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type ListScaleSetJobsDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this list scale set jobs default response has a 2xx status code
func (o *ListScaleSetJobsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list scale set jobs default response has a 3xx status code
func (o *ListScaleSetJobsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list scale set jobs default response has a 4xx status code
func (o *ListScaleSetJobsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list scale set jobs default response has a 5xx status code
func (o *ListScaleSetJobsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list scale set jobs default response a status code equal to that given
func (o *ListScaleSetJobsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list scale set jobs default response
func (o *ListScaleSetJobsDefault) Code() int {
	return o._statusCode
}

func (o *ListScaleSetJobsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /scalesets/{scalesetID}/jobs][%d] ListScaleSetJobs default %s", o._statusCode, payload)
}

func (o *ListScaleSetJobsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /scalesets/{scalesetID}/jobs][%d] ListScaleSetJobs default %s", o._statusCode, payload)
}

func (o *ListScaleSetJobsDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *ListScaleSetJobsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
