// Code generated by go-swagger; DO NOT EDIT.

package scalesets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListScalesetsParams creates a new ListScalesetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListScalesetsParams() *ListScalesetsParams {
	return &ListScalesetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListScalesetsParamsWithTimeout creates a new ListScalesetsParams object
// with the ability to set a timeout on a request.
func NewListScalesetsParamsWithTimeout(timeout time.Duration) *ListScalesetsParams {
	return &ListScalesetsParams{
		timeout: timeout,
	}
}

// NewListScalesetsParamsWithContext creates a new ListScalesetsParams object
// with the ability to set a context for a request.
func NewListScalesetsParamsWithContext(ctx context.Context) *ListScalesetsParams {
	return &ListScalesetsParams{
		Context: ctx,
	}
}

// NewListScalesetsParamsWithHTTPClient creates a new ListScalesetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListScalesetsParamsWithHTTPClient(client *http.Client) *ListScalesetsParams {
	return &ListScalesetsParams{
		HTTPClient: client,
	}
}

/*
ListScalesetsParams contains all the parameters to send to the API endpoint

	for the list scalesets operation.

	Typically these are written to a http.Request.
*/
type ListScalesetsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list scalesets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListScalesetsParams) WithDefaults() *ListScalesetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list scalesets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListScalesetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list scalesets params
func (o *ListScalesetsParams) WithTimeout(timeout time.Duration) *ListScalesetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list scalesets params
func (o *ListScalesetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list scalesets params
func (o *ListScalesetsParams) WithContext(ctx context.Context) *ListScalesetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list scalesets params
func (o *ListScalesetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list scalesets params
func (o *ListScalesetsParams) WithHTTPClient(client *http.Client) *ListScalesetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list scalesets params
func (o *ListScalesetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListScalesetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
