// Code generated by go-swagger; DO NOT EDIT.

package forge_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	garm_params "github.com/cloudbase/garm/params"
)

// NewCreateForgeInstancePoolParams creates a new CreateForgeInstancePoolParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateForgeInstancePoolParams() *CreateForgeInstancePoolParams {
	return &CreateForgeInstancePoolParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateForgeInstancePoolParamsWithTimeout creates a new CreateForgeInstancePoolParams object
// with the ability to set a timeout on a request.
func NewCreateForgeInstancePoolParamsWithTimeout(timeout time.Duration) *CreateForgeInstancePoolParams {
	return &CreateForgeInstancePoolParams{
		timeout: timeout,
	}
}

// NewCreateForgeInstancePoolParamsWithContext creates a new CreateForgeInstancePoolParams object
// with the ability to set a context for a request.
func NewCreateForgeInstancePoolParamsWithContext(ctx context.Context) *CreateForgeInstancePoolParams {
	return &CreateForgeInstancePoolParams{
		Context: ctx,
	}
}

// NewCreateForgeInstancePoolParamsWithHTTPClient creates a new CreateForgeInstancePoolParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateForgeInstancePoolParamsWithHTTPClient(client *http.Client) *CreateForgeInstancePoolParams {
	return &CreateForgeInstancePoolParams{
		HTTPClient: client,
	}
}

/*
CreateForgeInstancePoolParams contains all the parameters to send to the API endpoint

	for the create forge instance pool operation.

	Typically these are written to a http.Request.
*/
type CreateForgeInstancePoolParams struct {

	/* Body.

	   Parameters used when creating the forge instance pool.
	*/
	Body garm_params.CreatePoolParams

	/* ForgeInstanceID.

	   Forge instance ID.
	*/
	ForgeInstanceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create forge instance pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateForgeInstancePoolParams) WithDefaults() *CreateForgeInstancePoolParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create forge instance pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateForgeInstancePoolParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create forge instance pool params
func (o *CreateForgeInstancePoolParams) WithTimeout(timeout time.Duration) *CreateForgeInstancePoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create forge instance pool params
func (o *CreateForgeInstancePoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create forge instance pool params
func (o *CreateForgeInstancePoolParams) WithContext(ctx context.Context) *CreateForgeInstancePoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create forge instance pool params
func (o *CreateForgeInstancePoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create forge instance pool params
func (o *CreateForgeInstancePoolParams) WithHTTPClient(client *http.Client) *CreateForgeInstancePoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create forge instance pool params
func (o *CreateForgeInstancePoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create forge instance pool params
func (o *CreateForgeInstancePoolParams) WithBody(body garm_params.CreatePoolParams) *CreateForgeInstancePoolParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create forge instance pool params
func (o *CreateForgeInstancePoolParams) SetBody(body garm_params.CreatePoolParams) {
	o.Body = body
}

// WithForgeInstanceID adds the forgeInstanceID to the create forge instance pool params
func (o *CreateForgeInstancePoolParams) WithForgeInstanceID(forgeInstanceID string) *CreateForgeInstancePoolParams {
	o.SetForgeInstanceID(forgeInstanceID)
	return o
}

// SetForgeInstanceID adds the forgeInstanceId to the create forge instance pool params
func (o *CreateForgeInstancePoolParams) SetForgeInstanceID(forgeInstanceID string) {
	o.ForgeInstanceID = forgeInstanceID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateForgeInstancePoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param forgeInstanceID
	if err := r.SetPathParam("forgeInstanceID", o.ForgeInstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
