// Code generated by go-swagger; DO NOT EDIT.

package forge_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
)

// DeleteForgeInstancePoolReader is a Reader for the DeleteForgeInstancePool structure.
type DeleteForgeInstancePoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteForgeInstancePoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	result := NewDeleteForgeInstancePoolDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDeleteForgeInstancePoolDefault creates a DeleteForgeInstancePoolDefault with default headers values
func NewDeleteForgeInstancePoolDefault(code int) *DeleteForgeInstancePoolDefault {
	return &DeleteForgeInstancePoolDefault{
		_statusCode: code,
	}
}

/*
DeleteForgeInstancePoolDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type DeleteForgeInstancePoolDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this delete forge instance pool default response has a 2xx status code
func (o *DeleteForgeInstancePoolDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete forge instance pool default response has a 3xx status code
func (o *DeleteForgeInstancePoolDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete forge instance pool default response has a 4xx status code
func (o *DeleteForgeInstancePoolDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete forge instance pool default response has a 5xx status code
func (o *DeleteForgeInstancePoolDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete forge instance pool default response a status code equal to that given
func (o *DeleteForgeInstancePoolDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete forge instance pool default response
func (o *DeleteForgeInstancePoolDefault) Code() int {
	return o._statusCode
}

func (o *DeleteForgeInstancePoolDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /forge-instances/{forgeInstanceID}/pools/{poolID}][%d] DeleteForgeInstancePool default %s", o._statusCode, payload)
}

func (o *DeleteForgeInstancePoolDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /forge-instances/{forgeInstanceID}/pools/{poolID}][%d] DeleteForgeInstancePool default %s", o._statusCode, payload)
}

func (o *DeleteForgeInstancePoolDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *DeleteForgeInstancePoolDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
