// Code generated by go-swagger; DO NOT EDIT.

package forge_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
)

// DeleteForgeInstanceReader is a Reader for the DeleteForgeInstance structure.
type DeleteForgeInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteForgeInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	result := NewDeleteForgeInstanceDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDeleteForgeInstanceDefault creates a DeleteForgeInstanceDefault with default headers values
func NewDeleteForgeInstanceDefault(code int) *DeleteForgeInstanceDefault {
	return &DeleteForgeInstanceDefault{
		_statusCode: code,
	}
}

/*
DeleteForgeInstanceDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type DeleteForgeInstanceDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this delete forge instance default response has a 2xx status code
func (o *DeleteForgeInstanceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete forge instance default response has a 3xx status code
func (o *DeleteForgeInstanceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete forge instance default response has a 4xx status code
func (o *DeleteForgeInstanceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete forge instance default response has a 5xx status code
func (o *DeleteForgeInstanceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete forge instance default response a status code equal to that given
func (o *DeleteForgeInstanceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete forge instance default response
func (o *DeleteForgeInstanceDefault) Code() int {
	return o._statusCode
}

func (o *DeleteForgeInstanceDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /forge-instances/{forgeInstanceID}][%d] DeleteForgeInstance default %s", o._statusCode, payload)
}

func (o *DeleteForgeInstanceDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /forge-instances/{forgeInstanceID}][%d] DeleteForgeInstance default %s", o._statusCode, payload)
}

func (o *DeleteForgeInstanceDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *DeleteForgeInstanceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
