// Code generated by go-swagger; DO NOT EDIT.

package forge_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetForgeInstanceWebhookInfoParams creates a new GetForgeInstanceWebhookInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetForgeInstanceWebhookInfoParams() *GetForgeInstanceWebhookInfoParams {
	return &GetForgeInstanceWebhookInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetForgeInstanceWebhookInfoParamsWithTimeout creates a new GetForgeInstanceWebhookInfoParams object
// with the ability to set a timeout on a request.
func NewGetForgeInstanceWebhookInfoParamsWithTimeout(timeout time.Duration) *GetForgeInstanceWebhookInfoParams {
	return &GetForgeInstanceWebhookInfoParams{
		timeout: timeout,
	}
}

// NewGetForgeInstanceWebhookInfoParamsWithContext creates a new GetForgeInstanceWebhookInfoParams object
// with the ability to set a context for a request.
func NewGetForgeInstanceWebhookInfoParamsWithContext(ctx context.Context) *GetForgeInstanceWebhookInfoParams {
	return &GetForgeInstanceWebhookInfoParams{
		Context: ctx,
	}
}

// NewGetForgeInstanceWebhookInfoParamsWithHTTPClient creates a new GetForgeInstanceWebhookInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetForgeInstanceWebhookInfoParamsWithHTTPClient(client *http.Client) *GetForgeInstanceWebhookInfoParams {
	return &GetForgeInstanceWebhookInfoParams{
		HTTPClient: client,
	}
}

/*
GetForgeInstanceWebhookInfoParams contains all the parameters to send to the API endpoint

	for the get forge instance webhook info operation.

	Typically these are written to a http.Request.
*/
type GetForgeInstanceWebhookInfoParams struct {

	/* ForgeInstanceID.

	   Forge instance ID.
	*/
	ForgeInstanceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get forge instance webhook info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetForgeInstanceWebhookInfoParams) WithDefaults() *GetForgeInstanceWebhookInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get forge instance webhook info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetForgeInstanceWebhookInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get forge instance webhook info params
func (o *GetForgeInstanceWebhookInfoParams) WithTimeout(timeout time.Duration) *GetForgeInstanceWebhookInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get forge instance webhook info params
func (o *GetForgeInstanceWebhookInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get forge instance webhook info params
func (o *GetForgeInstanceWebhookInfoParams) WithContext(ctx context.Context) *GetForgeInstanceWebhookInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get forge instance webhook info params
func (o *GetForgeInstanceWebhookInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get forge instance webhook info params
func (o *GetForgeInstanceWebhookInfoParams) WithHTTPClient(client *http.Client) *GetForgeInstanceWebhookInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get forge instance webhook info params
func (o *GetForgeInstanceWebhookInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithForgeInstanceID adds the forgeInstanceID to the get forge instance webhook info params
func (o *GetForgeInstanceWebhookInfoParams) WithForgeInstanceID(forgeInstanceID string) *GetForgeInstanceWebhookInfoParams {
	o.SetForgeInstanceID(forgeInstanceID)
	return o
}

// SetForgeInstanceID adds the forgeInstanceId to the get forge instance webhook info params
func (o *GetForgeInstanceWebhookInfoParams) SetForgeInstanceID(forgeInstanceID string) {
	o.ForgeInstanceID = forgeInstanceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetForgeInstanceWebhookInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param forgeInstanceID
	if err := r.SetPathParam("forgeInstanceID", o.ForgeInstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
