// Code generated by go-swagger; DO NOT EDIT.

package forge_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
	garm_params "github.com/cloudbase/garm/params"
)

// GetForgeInstancePoolReader is a Reader for the GetForgeInstancePool structure.
type GetForgeInstancePoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetForgeInstancePoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetForgeInstancePoolOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetForgeInstancePoolDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetForgeInstancePoolOK creates a GetForgeInstancePoolOK with default headers values
func NewGetForgeInstancePoolOK() *GetForgeInstancePoolOK {
	return &GetForgeInstancePoolOK{}
}

/*
GetForgeInstancePoolOK describes a response with status code 200, with default header values.

Pool
*/
type GetForgeInstancePoolOK struct {
	Payload garm_params.Pool
}

// IsSuccess returns true when this get forge instance pool o k response has a 2xx status code
func (o *GetForgeInstancePoolOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get forge instance pool o k response has a 3xx status code
func (o *GetForgeInstancePoolOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get forge instance pool o k response has a 4xx status code
func (o *GetForgeInstancePoolOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get forge instance pool o k response has a 5xx status code
func (o *GetForgeInstancePoolOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get forge instance pool o k response a status code equal to that given
func (o *GetForgeInstancePoolOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get forge instance pool o k response
func (o *GetForgeInstancePoolOK) Code() int {
	return 200
}

func (o *GetForgeInstancePoolOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /forge-instances/{forgeInstanceID}/pools/{poolID}][%d] getForgeInstancePoolOK %s", 200, payload)
}

func (o *GetForgeInstancePoolOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /forge-instances/{forgeInstanceID}/pools/{poolID}][%d] getForgeInstancePoolOK %s", 200, payload)
}

func (o *GetForgeInstancePoolOK) GetPayload() garm_params.Pool {
	return o.Payload
}

func (o *GetForgeInstancePoolOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetForgeInstancePoolDefault creates a GetForgeInstancePoolDefault with default headers values
func NewGetForgeInstancePoolDefault(code int) *GetForgeInstancePoolDefault {
	return &GetForgeInstancePoolDefault{
		_statusCode: code,
	}
}

/*
GetForgeInstancePoolDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type GetForgeInstancePoolDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this get forge instance pool default response has a 2xx status code
func (o *GetForgeInstancePoolDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get forge instance pool default response has a 3xx status code
func (o *GetForgeInstancePoolDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get forge instance pool default response has a 4xx status code
func (o *GetForgeInstancePoolDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get forge instance pool default response has a 5xx status code
func (o *GetForgeInstancePoolDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get forge instance pool default response a status code equal to that given
func (o *GetForgeInstancePoolDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get forge instance pool default response
func (o *GetForgeInstancePoolDefault) Code() int {
	return o._statusCode
}

func (o *GetForgeInstancePoolDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /forge-instances/{forgeInstanceID}/pools/{poolID}][%d] GetForgeInstancePool default %s", o._statusCode, payload)
}

func (o *GetForgeInstancePoolDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /forge-instances/{forgeInstanceID}/pools/{poolID}][%d] GetForgeInstancePool default %s", o._statusCode, payload)
}

func (o *GetForgeInstancePoolDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *GetForgeInstancePoolDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
