// Code generated by go-swagger; DO NOT EDIT.

package forge_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	garm_params "github.com/cloudbase/garm/params"
)

// NewInstallForgeInstanceWebhookParams creates a new InstallForgeInstanceWebhookParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewInstallForgeInstanceWebhookParams() *InstallForgeInstanceWebhookParams {
	return &InstallForgeInstanceWebhookParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewInstallForgeInstanceWebhookParamsWithTimeout creates a new InstallForgeInstanceWebhookParams object
// with the ability to set a timeout on a request.
func NewInstallForgeInstanceWebhookParamsWithTimeout(timeout time.Duration) *InstallForgeInstanceWebhookParams {
	return &InstallForgeInstanceWebhookParams{
		timeout: timeout,
	}
}

// NewInstallForgeInstanceWebhookParamsWithContext creates a new InstallForgeInstanceWebhookParams object
// with the ability to set a context for a request.
func NewInstallForgeInstanceWebhookParamsWithContext(ctx context.Context) *InstallForgeInstanceWebhookParams {
	return &InstallForgeInstanceWebhookParams{
		Context: ctx,
	}
}

// NewInstallForgeInstanceWebhookParamsWithHTTPClient creates a new InstallForgeInstanceWebhookParams object
// with the ability to set a custom HTTPClient for a request.
func NewInstallForgeInstanceWebhookParamsWithHTTPClient(client *http.Client) *InstallForgeInstanceWebhookParams {
	return &InstallForgeInstanceWebhookParams{
		HTTPClient: client,
	}
}

/*
InstallForgeInstanceWebhookParams contains all the parameters to send to the API endpoint

	for the install forge instance webhook operation.

	Typically these are written to a http.Request.
*/
type InstallForgeInstanceWebhookParams struct {

	/* Body.

	   Parameters used when creating the forge instance webhook.
	*/
	Body garm_params.InstallWebhookParams

	/* ForgeInstanceID.

	   Forge instance ID.
	*/
	ForgeInstanceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the install forge instance webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InstallForgeInstanceWebhookParams) WithDefaults() *InstallForgeInstanceWebhookParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the install forge instance webhook params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InstallForgeInstanceWebhookParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the install forge instance webhook params
func (o *InstallForgeInstanceWebhookParams) WithTimeout(timeout time.Duration) *InstallForgeInstanceWebhookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the install forge instance webhook params
func (o *InstallForgeInstanceWebhookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the install forge instance webhook params
func (o *InstallForgeInstanceWebhookParams) WithContext(ctx context.Context) *InstallForgeInstanceWebhookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the install forge instance webhook params
func (o *InstallForgeInstanceWebhookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the install forge instance webhook params
func (o *InstallForgeInstanceWebhookParams) WithHTTPClient(client *http.Client) *InstallForgeInstanceWebhookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the install forge instance webhook params
func (o *InstallForgeInstanceWebhookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the install forge instance webhook params
func (o *InstallForgeInstanceWebhookParams) WithBody(body garm_params.InstallWebhookParams) *InstallForgeInstanceWebhookParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the install forge instance webhook params
func (o *InstallForgeInstanceWebhookParams) SetBody(body garm_params.InstallWebhookParams) {
	o.Body = body
}

// WithForgeInstanceID adds the forgeInstanceID to the install forge instance webhook params
func (o *InstallForgeInstanceWebhookParams) WithForgeInstanceID(forgeInstanceID string) *InstallForgeInstanceWebhookParams {
	o.SetForgeInstanceID(forgeInstanceID)
	return o
}

// SetForgeInstanceID adds the forgeInstanceId to the install forge instance webhook params
func (o *InstallForgeInstanceWebhookParams) SetForgeInstanceID(forgeInstanceID string) {
	o.ForgeInstanceID = forgeInstanceID
}

// WriteToRequest writes these params to a swagger request
func (o *InstallForgeInstanceWebhookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param forgeInstanceID
	if err := r.SetPathParam("forgeInstanceID", o.ForgeInstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
