// Code generated by go-swagger; DO NOT EDIT.

package forge_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
	garm_params "github.com/cloudbase/garm/params"
)

// ListForgeInstancePoolsReader is a Reader for the ListForgeInstancePools structure.
type ListForgeInstancePoolsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListForgeInstancePoolsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListForgeInstancePoolsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListForgeInstancePoolsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListForgeInstancePoolsOK creates a ListForgeInstancePoolsOK with default headers values
func NewListForgeInstancePoolsOK() *ListForgeInstancePoolsOK {
	return &ListForgeInstancePoolsOK{}
}

/*
ListForgeInstancePoolsOK describes a response with status code 200, with default header values.

Pools
*/
type ListForgeInstancePoolsOK struct {
	Payload garm_params.Pools
}

// IsSuccess returns true when this list forge instance pools o k response has a 2xx status code
func (o *ListForgeInstancePoolsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list forge instance pools o k response has a 3xx status code
func (o *ListForgeInstancePoolsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list forge instance pools o k response has a 4xx status code
func (o *ListForgeInstancePoolsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list forge instance pools o k response has a 5xx status code
func (o *ListForgeInstancePoolsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list forge instance pools o k response a status code equal to that given
func (o *ListForgeInstancePoolsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list forge instance pools o k response
func (o *ListForgeInstancePoolsOK) Code() int {
	return 200
}

func (o *ListForgeInstancePoolsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /forge-instances/{forgeInstanceID}/pools][%d] listForgeInstancePoolsOK %s", 200, payload)
}

func (o *ListForgeInstancePoolsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /forge-instances/{forgeInstanceID}/pools][%d] listForgeInstancePoolsOK %s", 200, payload)
}

func (o *ListForgeInstancePoolsOK) GetPayload() garm_params.Pools {
	return o.Payload
}

func (o *ListForgeInstancePoolsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListForgeInstancePoolsDefault creates a ListForgeInstancePoolsDefault with default headers values
func NewListForgeInstancePoolsDefault(code int) *ListForgeInstancePoolsDefault {
	return &ListForgeInstancePoolsDefault{
		_statusCode: code,
	}
}

/*
ListForgeInstancePoolsDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type ListForgeInstancePoolsDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this list forge instance pools default response has a 2xx status code
func (o *ListForgeInstancePoolsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list forge instance pools default response has a 3xx status code
func (o *ListForgeInstancePoolsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list forge instance pools default response has a 4xx status code
func (o *ListForgeInstancePoolsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list forge instance pools default response has a 5xx status code
func (o *ListForgeInstancePoolsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list forge instance pools default response a status code equal to that given
func (o *ListForgeInstancePoolsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list forge instance pools default response
func (o *ListForgeInstancePoolsDefault) Code() int {
	return o._statusCode
}

func (o *ListForgeInstancePoolsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /forge-instances/{forgeInstanceID}/pools][%d] ListForgeInstancePools default %s", o._statusCode, payload)
}

func (o *ListForgeInstancePoolsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /forge-instances/{forgeInstanceID}/pools][%d] ListForgeInstancePools default %s", o._statusCode, payload)
}

func (o *ListForgeInstancePoolsDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *ListForgeInstancePoolsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
