// Code generated by go-swagger; DO NOT EDIT.

package forge_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListForgeInstanceInstancesParams creates a new ListForgeInstanceInstancesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListForgeInstanceInstancesParams() *ListForgeInstanceInstancesParams {
	return &ListForgeInstanceInstancesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListForgeInstanceInstancesParamsWithTimeout creates a new ListForgeInstanceInstancesParams object
// with the ability to set a timeout on a request.
func NewListForgeInstanceInstancesParamsWithTimeout(timeout time.Duration) *ListForgeInstanceInstancesParams {
	return &ListForgeInstanceInstancesParams{
		timeout: timeout,
	}
}

// NewListForgeInstanceInstancesParamsWithContext creates a new ListForgeInstanceInstancesParams object
// with the ability to set a context for a request.
func NewListForgeInstanceInstancesParamsWithContext(ctx context.Context) *ListForgeInstanceInstancesParams {
	return &ListForgeInstanceInstancesParams{
		Context: ctx,
	}
}

// NewListForgeInstanceInstancesParamsWithHTTPClient creates a new ListForgeInstanceInstancesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListForgeInstanceInstancesParamsWithHTTPClient(client *http.Client) *ListForgeInstanceInstancesParams {
	return &ListForgeInstanceInstancesParams{
		HTTPClient: client,
	}
}

/*
ListForgeInstanceInstancesParams contains all the parameters to send to the API endpoint

	for the list forge instance instances operation.

	Typically these are written to a http.Request.
*/
type ListForgeInstanceInstancesParams struct {

	/* ForgeInstanceID.

	   Forge instance ID.
	*/
	ForgeInstanceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list forge instance instances params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListForgeInstanceInstancesParams) WithDefaults() *ListForgeInstanceInstancesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list forge instance instances params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListForgeInstanceInstancesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list forge instance instances params
func (o *ListForgeInstanceInstancesParams) WithTimeout(timeout time.Duration) *ListForgeInstanceInstancesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list forge instance instances params
func (o *ListForgeInstanceInstancesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list forge instance instances params
func (o *ListForgeInstanceInstancesParams) WithContext(ctx context.Context) *ListForgeInstanceInstancesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list forge instance instances params
func (o *ListForgeInstanceInstancesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list forge instance instances params
func (o *ListForgeInstanceInstancesParams) WithHTTPClient(client *http.Client) *ListForgeInstanceInstancesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list forge instance instances params
func (o *ListForgeInstanceInstancesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithForgeInstanceID adds the forgeInstanceID to the list forge instance instances params
func (o *ListForgeInstanceInstancesParams) WithForgeInstanceID(forgeInstanceID string) *ListForgeInstanceInstancesParams {
	o.SetForgeInstanceID(forgeInstanceID)
	return o
}

// SetForgeInstanceID adds the forgeInstanceId to the list forge instance instances params
func (o *ListForgeInstanceInstancesParams) SetForgeInstanceID(forgeInstanceID string) {
	o.ForgeInstanceID = forgeInstanceID
}

// WriteToRequest writes these params to a swagger request
func (o *ListForgeInstanceInstancesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param forgeInstanceID
	if err := r.SetPathParam("forgeInstanceID", o.ForgeInstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
