// Code generated by go-swagger; DO NOT EDIT.

package forge_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
	garm_params "github.com/cloudbase/garm/params"
)

// ListForgeInstanceInstancesReader is a Reader for the ListForgeInstanceInstances structure.
type ListForgeInstanceInstancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListForgeInstanceInstancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListForgeInstanceInstancesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListForgeInstanceInstancesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListForgeInstanceInstancesOK creates a ListForgeInstanceInstancesOK with default headers values
func NewListForgeInstanceInstancesOK() *ListForgeInstanceInstancesOK {
	return &ListForgeInstanceInstancesOK{}
}

/*
ListForgeInstanceInstancesOK describes a response with status code 200, with default header values.

Instances
*/
type ListForgeInstanceInstancesOK struct {
	Payload garm_params.Instances
}

// IsSuccess returns true when this list forge instance instances o k response has a 2xx status code
func (o *ListForgeInstanceInstancesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list forge instance instances o k response has a 3xx status code
func (o *ListForgeInstanceInstancesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list forge instance instances o k response has a 4xx status code
func (o *ListForgeInstanceInstancesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list forge instance instances o k response has a 5xx status code
func (o *ListForgeInstanceInstancesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list forge instance instances o k response a status code equal to that given
func (o *ListForgeInstanceInstancesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list forge instance instances o k response
func (o *ListForgeInstanceInstancesOK) Code() int {
	return 200
}

func (o *ListForgeInstanceInstancesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /forge-instances/{forgeInstanceID}/instances][%d] listForgeInstanceInstancesOK %s", 200, payload)
}

func (o *ListForgeInstanceInstancesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /forge-instances/{forgeInstanceID}/instances][%d] listForgeInstanceInstancesOK %s", 200, payload)
}

func (o *ListForgeInstanceInstancesOK) GetPayload() garm_params.Instances {
	return o.Payload
}

func (o *ListForgeInstanceInstancesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListForgeInstanceInstancesDefault creates a ListForgeInstanceInstancesDefault with default headers values
func NewListForgeInstanceInstancesDefault(code int) *ListForgeInstanceInstancesDefault {
	return &ListForgeInstanceInstancesDefault{
		_statusCode: code,
	}
}

/*
ListForgeInstanceInstancesDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type ListForgeInstanceInstancesDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this list forge instance instances default response has a 2xx status code
func (o *ListForgeInstanceInstancesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list forge instance instances default response has a 3xx status code
func (o *ListForgeInstanceInstancesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list forge instance instances default response has a 4xx status code
func (o *ListForgeInstanceInstancesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list forge instance instances default response has a 5xx status code
func (o *ListForgeInstanceInstancesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list forge instance instances default response a status code equal to that given
func (o *ListForgeInstanceInstancesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list forge instance instances default response
func (o *ListForgeInstanceInstancesDefault) Code() int {
	return o._statusCode
}

func (o *ListForgeInstanceInstancesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /forge-instances/{forgeInstanceID}/instances][%d] ListForgeInstanceInstances default %s", o._statusCode, payload)
}

func (o *ListForgeInstanceInstancesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /forge-instances/{forgeInstanceID}/instances][%d] ListForgeInstanceInstances default %s", o._statusCode, payload)
}

func (o *ListForgeInstanceInstancesDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *ListForgeInstanceInstancesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
