// Code generated by go-swagger; DO NOT EDIT.

package forge_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	garm_params "github.com/cloudbase/garm/params"
)

// NewUpdateForgeInstanceParams creates a new UpdateForgeInstanceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateForgeInstanceParams() *UpdateForgeInstanceParams {
	return &UpdateForgeInstanceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateForgeInstanceParamsWithTimeout creates a new UpdateForgeInstanceParams object
// with the ability to set a timeout on a request.
func NewUpdateForgeInstanceParamsWithTimeout(timeout time.Duration) *UpdateForgeInstanceParams {
	return &UpdateForgeInstanceParams{
		timeout: timeout,
	}
}

// NewUpdateForgeInstanceParamsWithContext creates a new UpdateForgeInstanceParams object
// with the ability to set a context for a request.
func NewUpdateForgeInstanceParamsWithContext(ctx context.Context) *UpdateForgeInstanceParams {
	return &UpdateForgeInstanceParams{
		Context: ctx,
	}
}

// NewUpdateForgeInstanceParamsWithHTTPClient creates a new UpdateForgeInstanceParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateForgeInstanceParamsWithHTTPClient(client *http.Client) *UpdateForgeInstanceParams {
	return &UpdateForgeInstanceParams{
		HTTPClient: client,
	}
}

/*
UpdateForgeInstanceParams contains all the parameters to send to the API endpoint

	for the update forge instance operation.

	Typically these are written to a http.Request.
*/
type UpdateForgeInstanceParams struct {

	/* Body.

	   Parameters used when updating the forge instance.
	*/
	Body garm_params.UpdateEntityParams

	/* ForgeInstanceID.

	   The ID of the forge instance to update.
	*/
	ForgeInstanceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update forge instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateForgeInstanceParams) WithDefaults() *UpdateForgeInstanceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update forge instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateForgeInstanceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update forge instance params
func (o *UpdateForgeInstanceParams) WithTimeout(timeout time.Duration) *UpdateForgeInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update forge instance params
func (o *UpdateForgeInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update forge instance params
func (o *UpdateForgeInstanceParams) WithContext(ctx context.Context) *UpdateForgeInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update forge instance params
func (o *UpdateForgeInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update forge instance params
func (o *UpdateForgeInstanceParams) WithHTTPClient(client *http.Client) *UpdateForgeInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update forge instance params
func (o *UpdateForgeInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update forge instance params
func (o *UpdateForgeInstanceParams) WithBody(body garm_params.UpdateEntityParams) *UpdateForgeInstanceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update forge instance params
func (o *UpdateForgeInstanceParams) SetBody(body garm_params.UpdateEntityParams) {
	o.Body = body
}

// WithForgeInstanceID adds the forgeInstanceID to the update forge instance params
func (o *UpdateForgeInstanceParams) WithForgeInstanceID(forgeInstanceID string) *UpdateForgeInstanceParams {
	o.SetForgeInstanceID(forgeInstanceID)
	return o
}

// SetForgeInstanceID adds the forgeInstanceId to the update forge instance params
func (o *UpdateForgeInstanceParams) SetForgeInstanceID(forgeInstanceID string) {
	o.ForgeInstanceID = forgeInstanceID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateForgeInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param forgeInstanceID
	if err := r.SetPathParam("forgeInstanceID", o.ForgeInstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
