version: "2"
linters:
  default: none
  enable:
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gosec
    - govet
    - importas
    - ineffassign
    - loggercheck
    - misspell
    - nakedret
    - nilerr
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
  settings:
    gosec:
      excludes:
        - G101
        - G115
        - G117
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - node_modules
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/cloudbase/garm)
    goimports:
      local-prefixes:
        - github.com/cloudbase/garm
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - node_modules
