// Code generated by go-swagger; DO NOT EDIT.

package controller_info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewControllerInfoParams creates a new ControllerInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewControllerInfoParams() *ControllerInfoParams {
	return &ControllerInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewControllerInfoParamsWithTimeout creates a new ControllerInfoParams object
// with the ability to set a timeout on a request.
func NewControllerInfoParamsWithTimeout(timeout time.Duration) *ControllerInfoParams {
	return &ControllerInfoParams{
		timeout: timeout,
	}
}

// NewControllerInfoParamsWithContext creates a new ControllerInfoParams object
// with the ability to set a context for a request.
func NewControllerInfoParamsWithContext(ctx context.Context) *ControllerInfoParams {
	return &ControllerInfoParams{
		Context: ctx,
	}
}

// NewControllerInfoParamsWithHTTPClient creates a new ControllerInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewControllerInfoParamsWithHTTPClient(client *http.Client) *ControllerInfoParams {
	return &ControllerInfoParams{
		HTTPClient: client,
	}
}

/*
ControllerInfoParams contains all the parameters to send to the API endpoint

	for the controller info operation.

	Typically these are written to a http.Request.
*/
type ControllerInfoParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the controller info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ControllerInfoParams) WithDefaults() *ControllerInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the controller info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ControllerInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the controller info params
func (o *ControllerInfoParams) WithTimeout(timeout time.Duration) *ControllerInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the controller info params
func (o *ControllerInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the controller info params
func (o *ControllerInfoParams) WithContext(ctx context.Context) *ControllerInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the controller info params
func (o *ControllerInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the controller info params
func (o *ControllerInfoParams) WithHTTPClient(client *http.Client) *ControllerInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the controller info params
func (o *ControllerInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ControllerInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
