// Code generated by go-swagger; DO NOT EDIT.

package templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
)

// RestoreTemplatesReader is a Reader for the RestoreTemplates structure.
type RestoreTemplatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RestoreTemplatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewRestoreTemplatesDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewRestoreTemplatesDefault creates a RestoreTemplatesDefault with default headers values
func NewRestoreTemplatesDefault(code int) *RestoreTemplatesDefault {
	return &RestoreTemplatesDefault{
		_statusCode: code,
	}
}

/*
RestoreTemplatesDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type RestoreTemplatesDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this restore templates default response has a 2xx status code
func (o *RestoreTemplatesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this restore templates default response has a 3xx status code
func (o *RestoreTemplatesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this restore templates default response has a 4xx status code
func (o *RestoreTemplatesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this restore templates default response has a 5xx status code
func (o *RestoreTemplatesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this restore templates default response a status code equal to that given
func (o *RestoreTemplatesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the restore templates default response
func (o *RestoreTemplatesDefault) Code() int {
	return o._statusCode
}

func (o *RestoreTemplatesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /templates/restore][%d] RestoreTemplates default %s", o._statusCode, payload)
}

func (o *RestoreTemplatesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /templates/restore][%d] RestoreTemplates default %s", o._statusCode, payload)
}

func (o *RestoreTemplatesDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *RestoreTemplatesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
