// Code generated by go-swagger; DO NOT EDIT.

package templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
	garm_params "github.com/cloudbase/garm/params"
)

// UpdateTemplateReader is a Reader for the UpdateTemplate structure.
type UpdateTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUpdateTemplateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateTemplateOK creates a UpdateTemplateOK with default headers values
func NewUpdateTemplateOK() *UpdateTemplateOK {
	return &UpdateTemplateOK{}
}

/*
UpdateTemplateOK describes a response with status code 200, with default header values.

Template
*/
type UpdateTemplateOK struct {
	Payload garm_params.Template
}

// IsSuccess returns true when this update template o k response has a 2xx status code
func (o *UpdateTemplateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update template o k response has a 3xx status code
func (o *UpdateTemplateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update template o k response has a 4xx status code
func (o *UpdateTemplateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update template o k response has a 5xx status code
func (o *UpdateTemplateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update template o k response a status code equal to that given
func (o *UpdateTemplateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update template o k response
func (o *UpdateTemplateOK) Code() int {
	return 200
}

func (o *UpdateTemplateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /templates/{templateID}][%d] updateTemplateOK %s", 200, payload)
}

func (o *UpdateTemplateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /templates/{templateID}][%d] updateTemplateOK %s", 200, payload)
}

func (o *UpdateTemplateOK) GetPayload() garm_params.Template {
	return o.Payload
}

func (o *UpdateTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateTemplateDefault creates a UpdateTemplateDefault with default headers values
func NewUpdateTemplateDefault(code int) *UpdateTemplateDefault {
	return &UpdateTemplateDefault{
		_statusCode: code,
	}
}

/*
UpdateTemplateDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type UpdateTemplateDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this update template default response has a 2xx status code
func (o *UpdateTemplateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this update template default response has a 3xx status code
func (o *UpdateTemplateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this update template default response has a 4xx status code
func (o *UpdateTemplateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this update template default response has a 5xx status code
func (o *UpdateTemplateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this update template default response a status code equal to that given
func (o *UpdateTemplateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the update template default response
func (o *UpdateTemplateDefault) Code() int {
	return o._statusCode
}

func (o *UpdateTemplateDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /templates/{templateID}][%d] UpdateTemplate default %s", o._statusCode, payload)
}

func (o *UpdateTemplateDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /templates/{templateID}][%d] UpdateTemplate default %s", o._statusCode, payload)
}

func (o *UpdateTemplateDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *UpdateTemplateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
