// Code generated by go-swagger; DO NOT EDIT.

package instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
)

// DeleteInstanceReader is a Reader for the DeleteInstance structure.
type DeleteInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewDeleteInstanceDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewDeleteInstanceDefault creates a DeleteInstanceDefault with default headers values
func NewDeleteInstanceDefault(code int) *DeleteInstanceDefault {
	return &DeleteInstanceDefault{
		_statusCode: code,
	}
}

/*
DeleteInstanceDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type DeleteInstanceDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this delete instance default response has a 2xx status code
func (o *DeleteInstanceDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete instance default response has a 3xx status code
func (o *DeleteInstanceDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete instance default response has a 4xx status code
func (o *DeleteInstanceDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete instance default response has a 5xx status code
func (o *DeleteInstanceDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete instance default response a status code equal to that given
func (o *DeleteInstanceDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete instance default response
func (o *DeleteInstanceDefault) Code() int {
	return o._statusCode
}

func (o *DeleteInstanceDefault) Error() string {
	return fmt.Sprintf("[DELETE /instances/{instanceName}][%d] DeleteInstance default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteInstanceDefault) String() string {
	return fmt.Sprintf("[DELETE /instances/{instanceName}][%d] DeleteInstance default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteInstanceDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *DeleteInstanceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
