// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	garm_params "github.com/cloudbase/garm/params"
)

// NewCreateOrgPoolParams creates a new CreateOrgPoolParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateOrgPoolParams() *CreateOrgPoolParams {
	return &CreateOrgPoolParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateOrgPoolParamsWithTimeout creates a new CreateOrgPoolParams object
// with the ability to set a timeout on a request.
func NewCreateOrgPoolParamsWithTimeout(timeout time.Duration) *CreateOrgPoolParams {
	return &CreateOrgPoolParams{
		timeout: timeout,
	}
}

// NewCreateOrgPoolParamsWithContext creates a new CreateOrgPoolParams object
// with the ability to set a context for a request.
func NewCreateOrgPoolParamsWithContext(ctx context.Context) *CreateOrgPoolParams {
	return &CreateOrgPoolParams{
		Context: ctx,
	}
}

// NewCreateOrgPoolParamsWithHTTPClient creates a new CreateOrgPoolParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateOrgPoolParamsWithHTTPClient(client *http.Client) *CreateOrgPoolParams {
	return &CreateOrgPoolParams{
		HTTPClient: client,
	}
}

/*
CreateOrgPoolParams contains all the parameters to send to the API endpoint

	for the create org pool operation.

	Typically these are written to a http.Request.
*/
type CreateOrgPoolParams struct {

	/* Body.

	   Parameters used when creating the organization pool.
	*/
	Body garm_params.CreatePoolParams

	/* OrgID.

	   Organization ID.
	*/
	OrgID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create org pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateOrgPoolParams) WithDefaults() *CreateOrgPoolParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create org pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateOrgPoolParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create org pool params
func (o *CreateOrgPoolParams) WithTimeout(timeout time.Duration) *CreateOrgPoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create org pool params
func (o *CreateOrgPoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create org pool params
func (o *CreateOrgPoolParams) WithContext(ctx context.Context) *CreateOrgPoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create org pool params
func (o *CreateOrgPoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create org pool params
func (o *CreateOrgPoolParams) WithHTTPClient(client *http.Client) *CreateOrgPoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create org pool params
func (o *CreateOrgPoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create org pool params
func (o *CreateOrgPoolParams) WithBody(body garm_params.CreatePoolParams) *CreateOrgPoolParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create org pool params
func (o *CreateOrgPoolParams) SetBody(body garm_params.CreatePoolParams) {
	o.Body = body
}

// WithOrgID adds the orgID to the create org pool params
func (o *CreateOrgPoolParams) WithOrgID(orgID string) *CreateOrgPoolParams {
	o.SetOrgID(orgID)
	return o
}

// SetOrgID adds the orgId to the create org pool params
func (o *CreateOrgPoolParams) SetOrgID(orgID string) {
	o.OrgID = orgID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateOrgPoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param orgID
	if err := r.SetPathParam("orgID", o.OrgID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
