// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
	garm_params "github.com/cloudbase/garm/params"
)

// CreateOrgScaleSetReader is a Reader for the CreateOrgScaleSet structure.
type CreateOrgScaleSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateOrgScaleSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateOrgScaleSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateOrgScaleSetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateOrgScaleSetOK creates a CreateOrgScaleSetOK with default headers values
func NewCreateOrgScaleSetOK() *CreateOrgScaleSetOK {
	return &CreateOrgScaleSetOK{}
}

/*
CreateOrgScaleSetOK describes a response with status code 200, with default header values.

ScaleSet
*/
type CreateOrgScaleSetOK struct {
	Payload garm_params.ScaleSet
}

// IsSuccess returns true when this create org scale set o k response has a 2xx status code
func (o *CreateOrgScaleSetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create org scale set o k response has a 3xx status code
func (o *CreateOrgScaleSetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create org scale set o k response has a 4xx status code
func (o *CreateOrgScaleSetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create org scale set o k response has a 5xx status code
func (o *CreateOrgScaleSetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create org scale set o k response a status code equal to that given
func (o *CreateOrgScaleSetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create org scale set o k response
func (o *CreateOrgScaleSetOK) Code() int {
	return 200
}

func (o *CreateOrgScaleSetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /organizations/{orgID}/scalesets][%d] createOrgScaleSetOK %s", 200, payload)
}

func (o *CreateOrgScaleSetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /organizations/{orgID}/scalesets][%d] createOrgScaleSetOK %s", 200, payload)
}

func (o *CreateOrgScaleSetOK) GetPayload() garm_params.ScaleSet {
	return o.Payload
}

func (o *CreateOrgScaleSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateOrgScaleSetDefault creates a CreateOrgScaleSetDefault with default headers values
func NewCreateOrgScaleSetDefault(code int) *CreateOrgScaleSetDefault {
	return &CreateOrgScaleSetDefault{
		_statusCode: code,
	}
}

/*
CreateOrgScaleSetDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type CreateOrgScaleSetDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this create org scale set default response has a 2xx status code
func (o *CreateOrgScaleSetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create org scale set default response has a 3xx status code
func (o *CreateOrgScaleSetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create org scale set default response has a 4xx status code
func (o *CreateOrgScaleSetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create org scale set default response has a 5xx status code
func (o *CreateOrgScaleSetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create org scale set default response a status code equal to that given
func (o *CreateOrgScaleSetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create org scale set default response
func (o *CreateOrgScaleSetDefault) Code() int {
	return o._statusCode
}

func (o *CreateOrgScaleSetDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /organizations/{orgID}/scalesets][%d] CreateOrgScaleSet default %s", o._statusCode, payload)
}

func (o *CreateOrgScaleSetDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /organizations/{orgID}/scalesets][%d] CreateOrgScaleSet default %s", o._statusCode, payload)
}

func (o *CreateOrgScaleSetDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *CreateOrgScaleSetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
