// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
	garm_params "github.com/cloudbase/garm/params"
)

// ListOrgsReader is a Reader for the ListOrgs structure.
type ListOrgsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListOrgsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListOrgsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListOrgsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListOrgsOK creates a ListOrgsOK with default headers values
func NewListOrgsOK() *ListOrgsOK {
	return &ListOrgsOK{}
}

/*
ListOrgsOK describes a response with status code 200, with default header values.

Organizations
*/
type ListOrgsOK struct {
	Payload garm_params.Organizations
}

// IsSuccess returns true when this list orgs o k response has a 2xx status code
func (o *ListOrgsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list orgs o k response has a 3xx status code
func (o *ListOrgsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list orgs o k response has a 4xx status code
func (o *ListOrgsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list orgs o k response has a 5xx status code
func (o *ListOrgsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list orgs o k response a status code equal to that given
func (o *ListOrgsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list orgs o k response
func (o *ListOrgsOK) Code() int {
	return 200
}

func (o *ListOrgsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations][%d] listOrgsOK %s", 200, payload)
}

func (o *ListOrgsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations][%d] listOrgsOK %s", 200, payload)
}

func (o *ListOrgsOK) GetPayload() garm_params.Organizations {
	return o.Payload
}

func (o *ListOrgsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListOrgsDefault creates a ListOrgsDefault with default headers values
func NewListOrgsDefault(code int) *ListOrgsDefault {
	return &ListOrgsDefault{
		_statusCode: code,
	}
}

/*
ListOrgsDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type ListOrgsDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this list orgs default response has a 2xx status code
func (o *ListOrgsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list orgs default response has a 3xx status code
func (o *ListOrgsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list orgs default response has a 4xx status code
func (o *ListOrgsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list orgs default response has a 5xx status code
func (o *ListOrgsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list orgs default response a status code equal to that given
func (o *ListOrgsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list orgs default response
func (o *ListOrgsDefault) Code() int {
	return o._statusCode
}

func (o *ListOrgsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations][%d] ListOrgs default %s", o._statusCode, payload)
}

func (o *ListOrgsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /organizations][%d] ListOrgs default %s", o._statusCode, payload)
}

func (o *ListOrgsDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *ListOrgsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
