// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
	garm_params "github.com/cloudbase/garm/params"
)

// ListOrgPoolsReader is a Reader for the ListOrgPools structure.
type ListOrgPoolsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListOrgPoolsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListOrgPoolsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListOrgPoolsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListOrgPoolsOK creates a ListOrgPoolsOK with default headers values
func NewListOrgPoolsOK() *ListOrgPoolsOK {
	return &ListOrgPoolsOK{}
}

/*
ListOrgPoolsOK describes a response with status code 200, with default header values.

Pools
*/
type ListOrgPoolsOK struct {
	Payload garm_params.Pools
}

// IsSuccess returns true when this list org pools o k response has a 2xx status code
func (o *ListOrgPoolsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list org pools o k response has a 3xx status code
func (o *ListOrgPoolsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list org pools o k response has a 4xx status code
func (o *ListOrgPoolsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list org pools o k response has a 5xx status code
func (o *ListOrgPoolsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list org pools o k response a status code equal to that given
func (o *ListOrgPoolsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list org pools o k response
func (o *ListOrgPoolsOK) Code() int {
	return 200
}

func (o *ListOrgPoolsOK) Error() string {
	return fmt.Sprintf("[GET /organizations/{orgID}/pools][%d] listOrgPoolsOK  %+v", 200, o.Payload)
}

func (o *ListOrgPoolsOK) String() string {
	return fmt.Sprintf("[GET /organizations/{orgID}/pools][%d] listOrgPoolsOK  %+v", 200, o.Payload)
}

func (o *ListOrgPoolsOK) GetPayload() garm_params.Pools {
	return o.Payload
}

func (o *ListOrgPoolsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListOrgPoolsDefault creates a ListOrgPoolsDefault with default headers values
func NewListOrgPoolsDefault(code int) *ListOrgPoolsDefault {
	return &ListOrgPoolsDefault{
		_statusCode: code,
	}
}

/*
ListOrgPoolsDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type ListOrgPoolsDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this list org pools default response has a 2xx status code
func (o *ListOrgPoolsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list org pools default response has a 3xx status code
func (o *ListOrgPoolsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list org pools default response has a 4xx status code
func (o *ListOrgPoolsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list org pools default response has a 5xx status code
func (o *ListOrgPoolsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list org pools default response a status code equal to that given
func (o *ListOrgPoolsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list org pools default response
func (o *ListOrgPoolsDefault) Code() int {
	return o._statusCode
}

func (o *ListOrgPoolsDefault) Error() string {
	return fmt.Sprintf("[GET /organizations/{orgID}/pools][%d] ListOrgPools default  %+v", o._statusCode, o.Payload)
}

func (o *ListOrgPoolsDefault) String() string {
	return fmt.Sprintf("[GET /organizations/{orgID}/pools][%d] ListOrgPools default  %+v", o._statusCode, o.Payload)
}

func (o *ListOrgPoolsDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *ListOrgPoolsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
