// Code generated by go-swagger; DO NOT EDIT.

package metrics_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMetricsTokenParams creates a new GetMetricsTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMetricsTokenParams() *GetMetricsTokenParams {
	return &GetMetricsTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMetricsTokenParamsWithTimeout creates a new GetMetricsTokenParams object
// with the ability to set a timeout on a request.
func NewGetMetricsTokenParamsWithTimeout(timeout time.Duration) *GetMetricsTokenParams {
	return &GetMetricsTokenParams{
		timeout: timeout,
	}
}

// NewGetMetricsTokenParamsWithContext creates a new GetMetricsTokenParams object
// with the ability to set a context for a request.
func NewGetMetricsTokenParamsWithContext(ctx context.Context) *GetMetricsTokenParams {
	return &GetMetricsTokenParams{
		Context: ctx,
	}
}

// NewGetMetricsTokenParamsWithHTTPClient creates a new GetMetricsTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMetricsTokenParamsWithHTTPClient(client *http.Client) *GetMetricsTokenParams {
	return &GetMetricsTokenParams{
		HTTPClient: client,
	}
}

/*
GetMetricsTokenParams contains all the parameters to send to the API endpoint

	for the get metrics token operation.

	Typically these are written to a http.Request.
*/
type GetMetricsTokenParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get metrics token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMetricsTokenParams) WithDefaults() *GetMetricsTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get metrics token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMetricsTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get metrics token params
func (o *GetMetricsTokenParams) WithTimeout(timeout time.Duration) *GetMetricsTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get metrics token params
func (o *GetMetricsTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get metrics token params
func (o *GetMetricsTokenParams) WithContext(ctx context.Context) *GetMetricsTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get metrics token params
func (o *GetMetricsTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get metrics token params
func (o *GetMetricsTokenParams) WithHTTPClient(client *http.Client) *GetMetricsTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get metrics token params
func (o *GetMetricsTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetMetricsTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
