{{- if not .Values.garm.admin.secretName -}}
{{- $secretName := include "garm.admin-secret-name" . -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}

{{- $password := "" -}}
{{- $jwtSecret := "" -}}
{{- $dbPassphrase := "" -}}

{{- if $existingSecret -}}
  {{- $password = index $existingSecret.data .Values.garm.admin.passwordKey | b64dec -}}
  {{- $jwtSecret = index $existingSecret.data .Values.garm.admin.jwtSecretKey | b64dec -}}
  {{- $dbPassphrase = index $existingSecret.data .Values.garm.admin.dbPassphraseKey | b64dec -}}
{{- else -}}
  {{- $password = randAlphaNum 40 -}}
  {{- $jwtSecret = randAlphaNum 64 -}}
  {{- $dbPassphrase = randAlphaNum 32 -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "garm.labels" . | nindent 4 }}
stringData:
  {{ .Values.garm.admin.usernameKey }}: {{ .Values.garm.admin.defaultUsername | quote }}
  {{ .Values.garm.admin.passwordKey }}: {{ $password | quote }}
  {{ .Values.garm.admin.emailKey }}: {{ .Values.garm.admin.defaultEmail | quote }}
  {{ .Values.garm.admin.jwtSecretKey }}: {{ $jwtSecret | quote }}
  {{ .Values.garm.admin.dbPassphraseKey }}: {{ $dbPassphrase | quote }}
{{- end -}}
