// Code generated by go-swagger; DO NOT EDIT.

package proxies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
	garm_params "github.com/cloudbase/garm/params"
)

// CreateProxyReader is a Reader for the CreateProxy structure.
type CreateProxyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateProxyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCreateProxyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateProxyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateProxyOK creates a CreateProxyOK with default headers values
func NewCreateProxyOK() *CreateProxyOK {
	return &CreateProxyOK{}
}

/*
CreateProxyOK describes a response with status code 200, with default header values.

Proxy
*/
type CreateProxyOK struct {
	Payload garm_params.Proxy
}

// IsSuccess returns true when this create proxy o k response has a 2xx status code
func (o *CreateProxyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create proxy o k response has a 3xx status code
func (o *CreateProxyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create proxy o k response has a 4xx status code
func (o *CreateProxyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create proxy o k response has a 5xx status code
func (o *CreateProxyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create proxy o k response a status code equal to that given
func (o *CreateProxyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create proxy o k response
func (o *CreateProxyOK) Code() int {
	return 200
}

func (o *CreateProxyOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /proxies][%d] createProxyOK %s", 200, payload)
}

func (o *CreateProxyOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /proxies][%d] createProxyOK %s", 200, payload)
}

func (o *CreateProxyOK) GetPayload() garm_params.Proxy {
	return o.Payload
}

func (o *CreateProxyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateProxyDefault creates a CreateProxyDefault with default headers values
func NewCreateProxyDefault(code int) *CreateProxyDefault {
	return &CreateProxyDefault{
		_statusCode: code,
	}
}

/*
CreateProxyDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type CreateProxyDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this create proxy default response has a 2xx status code
func (o *CreateProxyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this create proxy default response has a 3xx status code
func (o *CreateProxyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this create proxy default response has a 4xx status code
func (o *CreateProxyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this create proxy default response has a 5xx status code
func (o *CreateProxyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this create proxy default response a status code equal to that given
func (o *CreateProxyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the create proxy default response
func (o *CreateProxyDefault) Code() int {
	return o._statusCode
}

func (o *CreateProxyDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /proxies][%d] CreateProxy default %s", o._statusCode, payload)
}

func (o *CreateProxyDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /proxies][%d] CreateProxy default %s", o._statusCode, payload)
}

func (o *CreateProxyDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *CreateProxyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
