// Code generated by go-swagger; DO NOT EDIT.

package proxies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
	garm_params "github.com/cloudbase/garm/params"
)

// ListProxiesReader is a Reader for the ListProxies structure.
type ListProxiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListProxiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListProxiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListProxiesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListProxiesOK creates a ListProxiesOK with default headers values
func NewListProxiesOK() *ListProxiesOK {
	return &ListProxiesOK{}
}

/*
ListProxiesOK describes a response with status code 200, with default header values.

Proxies
*/
type ListProxiesOK struct {
	Payload garm_params.Proxies
}

// IsSuccess returns true when this list proxies o k response has a 2xx status code
func (o *ListProxiesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list proxies o k response has a 3xx status code
func (o *ListProxiesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list proxies o k response has a 4xx status code
func (o *ListProxiesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list proxies o k response has a 5xx status code
func (o *ListProxiesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list proxies o k response a status code equal to that given
func (o *ListProxiesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list proxies o k response
func (o *ListProxiesOK) Code() int {
	return 200
}

func (o *ListProxiesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /proxies][%d] listProxiesOK %s", 200, payload)
}

func (o *ListProxiesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /proxies][%d] listProxiesOK %s", 200, payload)
}

func (o *ListProxiesOK) GetPayload() garm_params.Proxies {
	return o.Payload
}

func (o *ListProxiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListProxiesDefault creates a ListProxiesDefault with default headers values
func NewListProxiesDefault(code int) *ListProxiesDefault {
	return &ListProxiesDefault{
		_statusCode: code,
	}
}

/*
ListProxiesDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type ListProxiesDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this list proxies default response has a 2xx status code
func (o *ListProxiesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list proxies default response has a 3xx status code
func (o *ListProxiesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list proxies default response has a 4xx status code
func (o *ListProxiesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list proxies default response has a 5xx status code
func (o *ListProxiesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list proxies default response a status code equal to that given
func (o *ListProxiesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list proxies default response
func (o *ListProxiesDefault) Code() int {
	return o._statusCode
}

func (o *ListProxiesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /proxies][%d] ListProxies default %s", o._statusCode, payload)
}

func (o *ListProxiesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /proxies][%d] ListProxies default %s", o._statusCode, payload)
}

func (o *ListProxiesDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *ListProxiesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
