// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	garm_params "github.com/cloudbase/garm/params"
)

// NewCreateRepoScaleSetByFriendlyNameParams creates a new CreateRepoScaleSetByFriendlyNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateRepoScaleSetByFriendlyNameParams() *CreateRepoScaleSetByFriendlyNameParams {
	return &CreateRepoScaleSetByFriendlyNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRepoScaleSetByFriendlyNameParamsWithTimeout creates a new CreateRepoScaleSetByFriendlyNameParams object
// with the ability to set a timeout on a request.
func NewCreateRepoScaleSetByFriendlyNameParamsWithTimeout(timeout time.Duration) *CreateRepoScaleSetByFriendlyNameParams {
	return &CreateRepoScaleSetByFriendlyNameParams{
		timeout: timeout,
	}
}

// NewCreateRepoScaleSetByFriendlyNameParamsWithContext creates a new CreateRepoScaleSetByFriendlyNameParams object
// with the ability to set a context for a request.
func NewCreateRepoScaleSetByFriendlyNameParamsWithContext(ctx context.Context) *CreateRepoScaleSetByFriendlyNameParams {
	return &CreateRepoScaleSetByFriendlyNameParams{
		Context: ctx,
	}
}

// NewCreateRepoScaleSetByFriendlyNameParamsWithHTTPClient creates a new CreateRepoScaleSetByFriendlyNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateRepoScaleSetByFriendlyNameParamsWithHTTPClient(client *http.Client) *CreateRepoScaleSetByFriendlyNameParams {
	return &CreateRepoScaleSetByFriendlyNameParams{
		HTTPClient: client,
	}
}

/*
CreateRepoScaleSetByFriendlyNameParams contains all the parameters to send to the API endpoint

	for the create repo scale set by friendly name operation.

	Typically these are written to a http.Request.
*/
type CreateRepoScaleSetByFriendlyNameParams struct {

	/* Body.

	   Parameters used when creating the repository scale set.
	*/
	Body garm_params.CreateScaleSetParams

	/* EndpointName.

	   Repository endpointName.
	*/
	EndpointName *string

	/* Owner.

	   Repository owner.
	*/
	Owner string

	/* Repo.

	   Repository name.
	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repo scale set by friendly name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRepoScaleSetByFriendlyNameParams) WithDefaults() *CreateRepoScaleSetByFriendlyNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repo scale set by friendly name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRepoScaleSetByFriendlyNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repo scale set by friendly name params
func (o *CreateRepoScaleSetByFriendlyNameParams) WithTimeout(timeout time.Duration) *CreateRepoScaleSetByFriendlyNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repo scale set by friendly name params
func (o *CreateRepoScaleSetByFriendlyNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repo scale set by friendly name params
func (o *CreateRepoScaleSetByFriendlyNameParams) WithContext(ctx context.Context) *CreateRepoScaleSetByFriendlyNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repo scale set by friendly name params
func (o *CreateRepoScaleSetByFriendlyNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repo scale set by friendly name params
func (o *CreateRepoScaleSetByFriendlyNameParams) WithHTTPClient(client *http.Client) *CreateRepoScaleSetByFriendlyNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repo scale set by friendly name params
func (o *CreateRepoScaleSetByFriendlyNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repo scale set by friendly name params
func (o *CreateRepoScaleSetByFriendlyNameParams) WithBody(body garm_params.CreateScaleSetParams) *CreateRepoScaleSetByFriendlyNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repo scale set by friendly name params
func (o *CreateRepoScaleSetByFriendlyNameParams) SetBody(body garm_params.CreateScaleSetParams) {
	o.Body = body
}

// WithEndpointName adds the endpointName to the create repo scale set by friendly name params
func (o *CreateRepoScaleSetByFriendlyNameParams) WithEndpointName(endpointName *string) *CreateRepoScaleSetByFriendlyNameParams {
	o.SetEndpointName(endpointName)
	return o
}

// SetEndpointName adds the endpointName to the create repo scale set by friendly name params
func (o *CreateRepoScaleSetByFriendlyNameParams) SetEndpointName(endpointName *string) {
	o.EndpointName = endpointName
}

// WithOwner adds the owner to the create repo scale set by friendly name params
func (o *CreateRepoScaleSetByFriendlyNameParams) WithOwner(owner string) *CreateRepoScaleSetByFriendlyNameParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the create repo scale set by friendly name params
func (o *CreateRepoScaleSetByFriendlyNameParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithRepo adds the repo to the create repo scale set by friendly name params
func (o *CreateRepoScaleSetByFriendlyNameParams) WithRepo(repo string) *CreateRepoScaleSetByFriendlyNameParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the create repo scale set by friendly name params
func (o *CreateRepoScaleSetByFriendlyNameParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRepoScaleSetByFriendlyNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if o.EndpointName != nil {

		// query param endpointName
		var qrEndpointName string

		if o.EndpointName != nil {
			qrEndpointName = *o.EndpointName
		}
		qEndpointName := qrEndpointName
		if qEndpointName != "" {

			if err := r.SetQueryParam("endpointName", qEndpointName); err != nil {
				return err
			}
		}
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
