// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	garm_params "github.com/cloudbase/garm/params"
)

// NewCreateRepoByNamePoolParams creates a new CreateRepoByNamePoolParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateRepoByNamePoolParams() *CreateRepoByNamePoolParams {
	return &CreateRepoByNamePoolParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRepoByNamePoolParamsWithTimeout creates a new CreateRepoByNamePoolParams object
// with the ability to set a timeout on a request.
func NewCreateRepoByNamePoolParamsWithTimeout(timeout time.Duration) *CreateRepoByNamePoolParams {
	return &CreateRepoByNamePoolParams{
		timeout: timeout,
	}
}

// NewCreateRepoByNamePoolParamsWithContext creates a new CreateRepoByNamePoolParams object
// with the ability to set a context for a request.
func NewCreateRepoByNamePoolParamsWithContext(ctx context.Context) *CreateRepoByNamePoolParams {
	return &CreateRepoByNamePoolParams{
		Context: ctx,
	}
}

// NewCreateRepoByNamePoolParamsWithHTTPClient creates a new CreateRepoByNamePoolParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateRepoByNamePoolParamsWithHTTPClient(client *http.Client) *CreateRepoByNamePoolParams {
	return &CreateRepoByNamePoolParams{
		HTTPClient: client,
	}
}

/*
CreateRepoByNamePoolParams contains all the parameters to send to the API endpoint

	for the create repo by name pool operation.

	Typically these are written to a http.Request.
*/
type CreateRepoByNamePoolParams struct {

	/* Body.

	   Parameters used when creating the repository pool.
	*/
	Body garm_params.CreatePoolParams

	/* EndpointName.

	   Repository endpointName.
	*/
	EndpointName *string

	/* Owner.

	   Repository owner.
	*/
	Owner string

	/* Repo.

	   Repository name.
	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create repo by name pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRepoByNamePoolParams) WithDefaults() *CreateRepoByNamePoolParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create repo by name pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRepoByNamePoolParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create repo by name pool params
func (o *CreateRepoByNamePoolParams) WithTimeout(timeout time.Duration) *CreateRepoByNamePoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repo by name pool params
func (o *CreateRepoByNamePoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repo by name pool params
func (o *CreateRepoByNamePoolParams) WithContext(ctx context.Context) *CreateRepoByNamePoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repo by name pool params
func (o *CreateRepoByNamePoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repo by name pool params
func (o *CreateRepoByNamePoolParams) WithHTTPClient(client *http.Client) *CreateRepoByNamePoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repo by name pool params
func (o *CreateRepoByNamePoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repo by name pool params
func (o *CreateRepoByNamePoolParams) WithBody(body garm_params.CreatePoolParams) *CreateRepoByNamePoolParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repo by name pool params
func (o *CreateRepoByNamePoolParams) SetBody(body garm_params.CreatePoolParams) {
	o.Body = body
}

// WithEndpointName adds the endpointName to the create repo by name pool params
func (o *CreateRepoByNamePoolParams) WithEndpointName(endpointName *string) *CreateRepoByNamePoolParams {
	o.SetEndpointName(endpointName)
	return o
}

// SetEndpointName adds the endpointName to the create repo by name pool params
func (o *CreateRepoByNamePoolParams) SetEndpointName(endpointName *string) {
	o.EndpointName = endpointName
}

// WithOwner adds the owner to the create repo by name pool params
func (o *CreateRepoByNamePoolParams) WithOwner(owner string) *CreateRepoByNamePoolParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the create repo by name pool params
func (o *CreateRepoByNamePoolParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithRepo adds the repo to the create repo by name pool params
func (o *CreateRepoByNamePoolParams) WithRepo(repo string) *CreateRepoByNamePoolParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the create repo by name pool params
func (o *CreateRepoByNamePoolParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRepoByNamePoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if o.EndpointName != nil {

		// query param endpointName
		var qrEndpointName string

		if o.EndpointName != nil {
			qrEndpointName = *o.EndpointName
		}
		qEndpointName := qrEndpointName
		if qEndpointName != "" {

			if err := r.SetQueryParam("endpointName", qEndpointName); err != nil {
				return err
			}
		}
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
