// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRepoByNamePoolParams creates a new GetRepoByNamePoolParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRepoByNamePoolParams() *GetRepoByNamePoolParams {
	return &GetRepoByNamePoolParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRepoByNamePoolParamsWithTimeout creates a new GetRepoByNamePoolParams object
// with the ability to set a timeout on a request.
func NewGetRepoByNamePoolParamsWithTimeout(timeout time.Duration) *GetRepoByNamePoolParams {
	return &GetRepoByNamePoolParams{
		timeout: timeout,
	}
}

// NewGetRepoByNamePoolParamsWithContext creates a new GetRepoByNamePoolParams object
// with the ability to set a context for a request.
func NewGetRepoByNamePoolParamsWithContext(ctx context.Context) *GetRepoByNamePoolParams {
	return &GetRepoByNamePoolParams{
		Context: ctx,
	}
}

// NewGetRepoByNamePoolParamsWithHTTPClient creates a new GetRepoByNamePoolParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRepoByNamePoolParamsWithHTTPClient(client *http.Client) *GetRepoByNamePoolParams {
	return &GetRepoByNamePoolParams{
		HTTPClient: client,
	}
}

/*
GetRepoByNamePoolParams contains all the parameters to send to the API endpoint

	for the get repo by name pool operation.

	Typically these are written to a http.Request.
*/
type GetRepoByNamePoolParams struct {

	/* EndpointName.

	   Repository endpointName.
	*/
	EndpointName *string

	/* Owner.

	   Repository owner.
	*/
	Owner string

	/* PoolID.

	   Pool ID.
	*/
	PoolID string

	/* Repo.

	   Repository name.
	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get repo by name pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRepoByNamePoolParams) WithDefaults() *GetRepoByNamePoolParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get repo by name pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRepoByNamePoolParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get repo by name pool params
func (o *GetRepoByNamePoolParams) WithTimeout(timeout time.Duration) *GetRepoByNamePoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repo by name pool params
func (o *GetRepoByNamePoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repo by name pool params
func (o *GetRepoByNamePoolParams) WithContext(ctx context.Context) *GetRepoByNamePoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repo by name pool params
func (o *GetRepoByNamePoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repo by name pool params
func (o *GetRepoByNamePoolParams) WithHTTPClient(client *http.Client) *GetRepoByNamePoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repo by name pool params
func (o *GetRepoByNamePoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEndpointName adds the endpointName to the get repo by name pool params
func (o *GetRepoByNamePoolParams) WithEndpointName(endpointName *string) *GetRepoByNamePoolParams {
	o.SetEndpointName(endpointName)
	return o
}

// SetEndpointName adds the endpointName to the get repo by name pool params
func (o *GetRepoByNamePoolParams) SetEndpointName(endpointName *string) {
	o.EndpointName = endpointName
}

// WithOwner adds the owner to the get repo by name pool params
func (o *GetRepoByNamePoolParams) WithOwner(owner string) *GetRepoByNamePoolParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the get repo by name pool params
func (o *GetRepoByNamePoolParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithPoolID adds the poolID to the get repo by name pool params
func (o *GetRepoByNamePoolParams) WithPoolID(poolID string) *GetRepoByNamePoolParams {
	o.SetPoolID(poolID)
	return o
}

// SetPoolID adds the poolId to the get repo by name pool params
func (o *GetRepoByNamePoolParams) SetPoolID(poolID string) {
	o.PoolID = poolID
}

// WithRepo adds the repo to the get repo by name pool params
func (o *GetRepoByNamePoolParams) WithRepo(repo string) *GetRepoByNamePoolParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the get repo by name pool params
func (o *GetRepoByNamePoolParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepoByNamePoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.EndpointName != nil {

		// query param endpointName
		var qrEndpointName string

		if o.EndpointName != nil {
			qrEndpointName = *o.EndpointName
		}
		qEndpointName := qrEndpointName
		if qEndpointName != "" {

			if err := r.SetQueryParam("endpointName", qEndpointName); err != nil {
				return err
			}
		}
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param poolID
	if err := r.SetPathParam("poolID", o.PoolID); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
