// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRepoByFriendlyNameParams creates a new GetRepoByFriendlyNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRepoByFriendlyNameParams() *GetRepoByFriendlyNameParams {
	return &GetRepoByFriendlyNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRepoByFriendlyNameParamsWithTimeout creates a new GetRepoByFriendlyNameParams object
// with the ability to set a timeout on a request.
func NewGetRepoByFriendlyNameParamsWithTimeout(timeout time.Duration) *GetRepoByFriendlyNameParams {
	return &GetRepoByFriendlyNameParams{
		timeout: timeout,
	}
}

// NewGetRepoByFriendlyNameParamsWithContext creates a new GetRepoByFriendlyNameParams object
// with the ability to set a context for a request.
func NewGetRepoByFriendlyNameParamsWithContext(ctx context.Context) *GetRepoByFriendlyNameParams {
	return &GetRepoByFriendlyNameParams{
		Context: ctx,
	}
}

// NewGetRepoByFriendlyNameParamsWithHTTPClient creates a new GetRepoByFriendlyNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRepoByFriendlyNameParamsWithHTTPClient(client *http.Client) *GetRepoByFriendlyNameParams {
	return &GetRepoByFriendlyNameParams{
		HTTPClient: client,
	}
}

/*
GetRepoByFriendlyNameParams contains all the parameters to send to the API endpoint

	for the get repo by friendly name operation.

	Typically these are written to a http.Request.
*/
type GetRepoByFriendlyNameParams struct {

	/* EndpointName.

	   endpointName of the repository to fetch.
	*/
	EndpointName *string

	/* Owner.

	   owner of the repository to fetch.
	*/
	Owner string

	/* Repo.

	   name of the repository to fetch.
	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get repo by friendly name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRepoByFriendlyNameParams) WithDefaults() *GetRepoByFriendlyNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get repo by friendly name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRepoByFriendlyNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get repo by friendly name params
func (o *GetRepoByFriendlyNameParams) WithTimeout(timeout time.Duration) *GetRepoByFriendlyNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repo by friendly name params
func (o *GetRepoByFriendlyNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repo by friendly name params
func (o *GetRepoByFriendlyNameParams) WithContext(ctx context.Context) *GetRepoByFriendlyNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repo by friendly name params
func (o *GetRepoByFriendlyNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repo by friendly name params
func (o *GetRepoByFriendlyNameParams) WithHTTPClient(client *http.Client) *GetRepoByFriendlyNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repo by friendly name params
func (o *GetRepoByFriendlyNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEndpointName adds the endpointName to the get repo by friendly name params
func (o *GetRepoByFriendlyNameParams) WithEndpointName(endpointName *string) *GetRepoByFriendlyNameParams {
	o.SetEndpointName(endpointName)
	return o
}

// SetEndpointName adds the endpointName to the get repo by friendly name params
func (o *GetRepoByFriendlyNameParams) SetEndpointName(endpointName *string) {
	o.EndpointName = endpointName
}

// WithOwner adds the owner to the get repo by friendly name params
func (o *GetRepoByFriendlyNameParams) WithOwner(owner string) *GetRepoByFriendlyNameParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the get repo by friendly name params
func (o *GetRepoByFriendlyNameParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithRepo adds the repo to the get repo by friendly name params
func (o *GetRepoByFriendlyNameParams) WithRepo(repo string) *GetRepoByFriendlyNameParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the get repo by friendly name params
func (o *GetRepoByFriendlyNameParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepoByFriendlyNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.EndpointName != nil {

		// query param endpointName
		var qrEndpointName string

		if o.EndpointName != nil {
			qrEndpointName = *o.EndpointName
		}
		qEndpointName := qrEndpointName
		if qEndpointName != "" {

			if err := r.SetQueryParam("endpointName", qEndpointName); err != nil {
				return err
			}
		}
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
