// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
	garm_params "github.com/cloudbase/garm/params"
)

// ListRepoInstancesByFriendlyNameReader is a Reader for the ListRepoInstancesByFriendlyName structure.
type ListRepoInstancesByFriendlyNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListRepoInstancesByFriendlyNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListRepoInstancesByFriendlyNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListRepoInstancesByFriendlyNameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListRepoInstancesByFriendlyNameOK creates a ListRepoInstancesByFriendlyNameOK with default headers values
func NewListRepoInstancesByFriendlyNameOK() *ListRepoInstancesByFriendlyNameOK {
	return &ListRepoInstancesByFriendlyNameOK{}
}

/*
ListRepoInstancesByFriendlyNameOK describes a response with status code 200, with default header values.

Instances
*/
type ListRepoInstancesByFriendlyNameOK struct {
	Payload garm_params.Instances
}

// IsSuccess returns true when this list repo instances by friendly name o k response has a 2xx status code
func (o *ListRepoInstancesByFriendlyNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list repo instances by friendly name o k response has a 3xx status code
func (o *ListRepoInstancesByFriendlyNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list repo instances by friendly name o k response has a 4xx status code
func (o *ListRepoInstancesByFriendlyNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list repo instances by friendly name o k response has a 5xx status code
func (o *ListRepoInstancesByFriendlyNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list repo instances by friendly name o k response a status code equal to that given
func (o *ListRepoInstancesByFriendlyNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list repo instances by friendly name o k response
func (o *ListRepoInstancesByFriendlyNameOK) Code() int {
	return 200
}

func (o *ListRepoInstancesByFriendlyNameOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /repositories/{owner}/{repo}/instances][%d] listRepoInstancesByFriendlyNameOK %s", 200, payload)
}

func (o *ListRepoInstancesByFriendlyNameOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /repositories/{owner}/{repo}/instances][%d] listRepoInstancesByFriendlyNameOK %s", 200, payload)
}

func (o *ListRepoInstancesByFriendlyNameOK) GetPayload() garm_params.Instances {
	return o.Payload
}

func (o *ListRepoInstancesByFriendlyNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListRepoInstancesByFriendlyNameDefault creates a ListRepoInstancesByFriendlyNameDefault with default headers values
func NewListRepoInstancesByFriendlyNameDefault(code int) *ListRepoInstancesByFriendlyNameDefault {
	return &ListRepoInstancesByFriendlyNameDefault{
		_statusCode: code,
	}
}

/*
ListRepoInstancesByFriendlyNameDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type ListRepoInstancesByFriendlyNameDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this list repo instances by friendly name default response has a 2xx status code
func (o *ListRepoInstancesByFriendlyNameDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list repo instances by friendly name default response has a 3xx status code
func (o *ListRepoInstancesByFriendlyNameDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list repo instances by friendly name default response has a 4xx status code
func (o *ListRepoInstancesByFriendlyNameDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list repo instances by friendly name default response has a 5xx status code
func (o *ListRepoInstancesByFriendlyNameDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list repo instances by friendly name default response a status code equal to that given
func (o *ListRepoInstancesByFriendlyNameDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list repo instances by friendly name default response
func (o *ListRepoInstancesByFriendlyNameDefault) Code() int {
	return o._statusCode
}

func (o *ListRepoInstancesByFriendlyNameDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /repositories/{owner}/{repo}/instances][%d] ListRepoInstancesByFriendlyName default %s", o._statusCode, payload)
}

func (o *ListRepoInstancesByFriendlyNameDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /repositories/{owner}/{repo}/instances][%d] ListRepoInstancesByFriendlyName default %s", o._statusCode, payload)
}

func (o *ListRepoInstancesByFriendlyNameDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *ListRepoInstancesByFriendlyNameDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
