// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	garm_params "github.com/cloudbase/garm/params"
)

// NewUpdateRepoPoolByFriendlyNameParams creates a new UpdateRepoPoolByFriendlyNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateRepoPoolByFriendlyNameParams() *UpdateRepoPoolByFriendlyNameParams {
	return &UpdateRepoPoolByFriendlyNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRepoPoolByFriendlyNameParamsWithTimeout creates a new UpdateRepoPoolByFriendlyNameParams object
// with the ability to set a timeout on a request.
func NewUpdateRepoPoolByFriendlyNameParamsWithTimeout(timeout time.Duration) *UpdateRepoPoolByFriendlyNameParams {
	return &UpdateRepoPoolByFriendlyNameParams{
		timeout: timeout,
	}
}

// NewUpdateRepoPoolByFriendlyNameParamsWithContext creates a new UpdateRepoPoolByFriendlyNameParams object
// with the ability to set a context for a request.
func NewUpdateRepoPoolByFriendlyNameParamsWithContext(ctx context.Context) *UpdateRepoPoolByFriendlyNameParams {
	return &UpdateRepoPoolByFriendlyNameParams{
		Context: ctx,
	}
}

// NewUpdateRepoPoolByFriendlyNameParamsWithHTTPClient creates a new UpdateRepoPoolByFriendlyNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateRepoPoolByFriendlyNameParamsWithHTTPClient(client *http.Client) *UpdateRepoPoolByFriendlyNameParams {
	return &UpdateRepoPoolByFriendlyNameParams{
		HTTPClient: client,
	}
}

/*
UpdateRepoPoolByFriendlyNameParams contains all the parameters to send to the API endpoint

	for the update repo pool by friendly name operation.

	Typically these are written to a http.Request.
*/
type UpdateRepoPoolByFriendlyNameParams struct {

	/* Body.

	   Parameters used when updating the repository pool.
	*/
	Body garm_params.UpdatePoolParams

	/* EndpointName.

	   Repository endpointName.
	*/
	EndpointName *string

	/* Owner.

	   Repository owner.
	*/
	Owner string

	/* PoolID.

	   ID of the repository pool to update.
	*/
	PoolID string

	/* Repo.

	   Repository name.
	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update repo pool by friendly name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRepoPoolByFriendlyNameParams) WithDefaults() *UpdateRepoPoolByFriendlyNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update repo pool by friendly name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRepoPoolByFriendlyNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) WithTimeout(timeout time.Duration) *UpdateRepoPoolByFriendlyNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) WithContext(ctx context.Context) *UpdateRepoPoolByFriendlyNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) WithHTTPClient(client *http.Client) *UpdateRepoPoolByFriendlyNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) WithBody(body garm_params.UpdatePoolParams) *UpdateRepoPoolByFriendlyNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) SetBody(body garm_params.UpdatePoolParams) {
	o.Body = body
}

// WithEndpointName adds the endpointName to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) WithEndpointName(endpointName *string) *UpdateRepoPoolByFriendlyNameParams {
	o.SetEndpointName(endpointName)
	return o
}

// SetEndpointName adds the endpointName to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) SetEndpointName(endpointName *string) {
	o.EndpointName = endpointName
}

// WithOwner adds the owner to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) WithOwner(owner string) *UpdateRepoPoolByFriendlyNameParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithPoolID adds the poolID to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) WithPoolID(poolID string) *UpdateRepoPoolByFriendlyNameParams {
	o.SetPoolID(poolID)
	return o
}

// SetPoolID adds the poolId to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) SetPoolID(poolID string) {
	o.PoolID = poolID
}

// WithRepo adds the repo to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) WithRepo(repo string) *UpdateRepoPoolByFriendlyNameParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the update repo pool by friendly name params
func (o *UpdateRepoPoolByFriendlyNameParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRepoPoolByFriendlyNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if o.EndpointName != nil {

		// query param endpointName
		var qrEndpointName string

		if o.EndpointName != nil {
			qrEndpointName = *o.EndpointName
		}
		qEndpointName := qrEndpointName
		if qEndpointName != "" {

			if err := r.SetQueryParam("endpointName", qEndpointName); err != nil {
				return err
			}
		}
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param poolID
	if err := r.SetPathParam("poolID", o.PoolID); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
