// Code generated by go-swagger; DO NOT EDIT.

package repositories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	garm_params "github.com/cloudbase/garm/params"
)

// NewUpdateRepoByFriendlyNameParams creates a new UpdateRepoByFriendlyNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateRepoByFriendlyNameParams() *UpdateRepoByFriendlyNameParams {
	return &UpdateRepoByFriendlyNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRepoByFriendlyNameParamsWithTimeout creates a new UpdateRepoByFriendlyNameParams object
// with the ability to set a timeout on a request.
func NewUpdateRepoByFriendlyNameParamsWithTimeout(timeout time.Duration) *UpdateRepoByFriendlyNameParams {
	return &UpdateRepoByFriendlyNameParams{
		timeout: timeout,
	}
}

// NewUpdateRepoByFriendlyNameParamsWithContext creates a new UpdateRepoByFriendlyNameParams object
// with the ability to set a context for a request.
func NewUpdateRepoByFriendlyNameParamsWithContext(ctx context.Context) *UpdateRepoByFriendlyNameParams {
	return &UpdateRepoByFriendlyNameParams{
		Context: ctx,
	}
}

// NewUpdateRepoByFriendlyNameParamsWithHTTPClient creates a new UpdateRepoByFriendlyNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateRepoByFriendlyNameParamsWithHTTPClient(client *http.Client) *UpdateRepoByFriendlyNameParams {
	return &UpdateRepoByFriendlyNameParams{
		HTTPClient: client,
	}
}

/*
UpdateRepoByFriendlyNameParams contains all the parameters to send to the API endpoint

	for the update repo by friendly name operation.

	Typically these are written to a http.Request.
*/
type UpdateRepoByFriendlyNameParams struct {

	/* Body.

	   Parameters used when updating the repository.
	*/
	Body garm_params.UpdateEntityParams

	/* EndpointName.

	   endpointName of the repository to update.
	*/
	EndpointName *string

	/* Owner.

	   owner of the repository to update.
	*/
	Owner string

	/* Repo.

	   name of the repository to update.
	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update repo by friendly name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRepoByFriendlyNameParams) WithDefaults() *UpdateRepoByFriendlyNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update repo by friendly name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRepoByFriendlyNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update repo by friendly name params
func (o *UpdateRepoByFriendlyNameParams) WithTimeout(timeout time.Duration) *UpdateRepoByFriendlyNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update repo by friendly name params
func (o *UpdateRepoByFriendlyNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update repo by friendly name params
func (o *UpdateRepoByFriendlyNameParams) WithContext(ctx context.Context) *UpdateRepoByFriendlyNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update repo by friendly name params
func (o *UpdateRepoByFriendlyNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update repo by friendly name params
func (o *UpdateRepoByFriendlyNameParams) WithHTTPClient(client *http.Client) *UpdateRepoByFriendlyNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update repo by friendly name params
func (o *UpdateRepoByFriendlyNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update repo by friendly name params
func (o *UpdateRepoByFriendlyNameParams) WithBody(body garm_params.UpdateEntityParams) *UpdateRepoByFriendlyNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update repo by friendly name params
func (o *UpdateRepoByFriendlyNameParams) SetBody(body garm_params.UpdateEntityParams) {
	o.Body = body
}

// WithEndpointName adds the endpointName to the update repo by friendly name params
func (o *UpdateRepoByFriendlyNameParams) WithEndpointName(endpointName *string) *UpdateRepoByFriendlyNameParams {
	o.SetEndpointName(endpointName)
	return o
}

// SetEndpointName adds the endpointName to the update repo by friendly name params
func (o *UpdateRepoByFriendlyNameParams) SetEndpointName(endpointName *string) {
	o.EndpointName = endpointName
}

// WithOwner adds the owner to the update repo by friendly name params
func (o *UpdateRepoByFriendlyNameParams) WithOwner(owner string) *UpdateRepoByFriendlyNameParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the update repo by friendly name params
func (o *UpdateRepoByFriendlyNameParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithRepo adds the repo to the update repo by friendly name params
func (o *UpdateRepoByFriendlyNameParams) WithRepo(repo string) *UpdateRepoByFriendlyNameParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the update repo by friendly name params
func (o *UpdateRepoByFriendlyNameParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRepoByFriendlyNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if o.EndpointName != nil {

		// query param endpointName
		var qrEndpointName string

		if o.EndpointName != nil {
			qrEndpointName = *o.EndpointName
		}
		qEndpointName := qrEndpointName
		if qEndpointName != "" {

			if err := r.SetQueryParam("endpointName", qEndpointName); err != nil {
				return err
			}
		}
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
