// Code generated by go-swagger; DO NOT EDIT.

package enterprises

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteEnterprisePoolParams creates a new DeleteEnterprisePoolParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteEnterprisePoolParams() *DeleteEnterprisePoolParams {
	return &DeleteEnterprisePoolParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteEnterprisePoolParamsWithTimeout creates a new DeleteEnterprisePoolParams object
// with the ability to set a timeout on a request.
func NewDeleteEnterprisePoolParamsWithTimeout(timeout time.Duration) *DeleteEnterprisePoolParams {
	return &DeleteEnterprisePoolParams{
		timeout: timeout,
	}
}

// NewDeleteEnterprisePoolParamsWithContext creates a new DeleteEnterprisePoolParams object
// with the ability to set a context for a request.
func NewDeleteEnterprisePoolParamsWithContext(ctx context.Context) *DeleteEnterprisePoolParams {
	return &DeleteEnterprisePoolParams{
		Context: ctx,
	}
}

// NewDeleteEnterprisePoolParamsWithHTTPClient creates a new DeleteEnterprisePoolParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteEnterprisePoolParamsWithHTTPClient(client *http.Client) *DeleteEnterprisePoolParams {
	return &DeleteEnterprisePoolParams{
		HTTPClient: client,
	}
}

/*
DeleteEnterprisePoolParams contains all the parameters to send to the API endpoint

	for the delete enterprise pool operation.

	Typically these are written to a http.Request.
*/
type DeleteEnterprisePoolParams struct {

	/* EnterpriseID.

	   Enterprise ID.
	*/
	EnterpriseID string

	/* PoolID.

	   ID of the enterprise pool to delete.
	*/
	PoolID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete enterprise pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteEnterprisePoolParams) WithDefaults() *DeleteEnterprisePoolParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete enterprise pool params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteEnterprisePoolParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete enterprise pool params
func (o *DeleteEnterprisePoolParams) WithTimeout(timeout time.Duration) *DeleteEnterprisePoolParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete enterprise pool params
func (o *DeleteEnterprisePoolParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete enterprise pool params
func (o *DeleteEnterprisePoolParams) WithContext(ctx context.Context) *DeleteEnterprisePoolParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete enterprise pool params
func (o *DeleteEnterprisePoolParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete enterprise pool params
func (o *DeleteEnterprisePoolParams) WithHTTPClient(client *http.Client) *DeleteEnterprisePoolParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete enterprise pool params
func (o *DeleteEnterprisePoolParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnterpriseID adds the enterpriseID to the delete enterprise pool params
func (o *DeleteEnterprisePoolParams) WithEnterpriseID(enterpriseID string) *DeleteEnterprisePoolParams {
	o.SetEnterpriseID(enterpriseID)
	return o
}

// SetEnterpriseID adds the enterpriseId to the delete enterprise pool params
func (o *DeleteEnterprisePoolParams) SetEnterpriseID(enterpriseID string) {
	o.EnterpriseID = enterpriseID
}

// WithPoolID adds the poolID to the delete enterprise pool params
func (o *DeleteEnterprisePoolParams) WithPoolID(poolID string) *DeleteEnterprisePoolParams {
	o.SetPoolID(poolID)
	return o
}

// SetPoolID adds the poolId to the delete enterprise pool params
func (o *DeleteEnterprisePoolParams) SetPoolID(poolID string) {
	o.PoolID = poolID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteEnterprisePoolParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param enterpriseID
	if err := r.SetPathParam("enterpriseID", o.EnterpriseID); err != nil {
		return err
	}

	// path param poolID
	if err := r.SetPathParam("poolID", o.PoolID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
