// Code generated by go-swagger; DO NOT EDIT.

package enterprises

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEnterpriseParams creates a new GetEnterpriseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEnterpriseParams() *GetEnterpriseParams {
	return &GetEnterpriseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetEnterpriseParamsWithTimeout creates a new GetEnterpriseParams object
// with the ability to set a timeout on a request.
func NewGetEnterpriseParamsWithTimeout(timeout time.Duration) *GetEnterpriseParams {
	return &GetEnterpriseParams{
		timeout: timeout,
	}
}

// NewGetEnterpriseParamsWithContext creates a new GetEnterpriseParams object
// with the ability to set a context for a request.
func NewGetEnterpriseParamsWithContext(ctx context.Context) *GetEnterpriseParams {
	return &GetEnterpriseParams{
		Context: ctx,
	}
}

// NewGetEnterpriseParamsWithHTTPClient creates a new GetEnterpriseParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEnterpriseParamsWithHTTPClient(client *http.Client) *GetEnterpriseParams {
	return &GetEnterpriseParams{
		HTTPClient: client,
	}
}

/*
GetEnterpriseParams contains all the parameters to send to the API endpoint

	for the get enterprise operation.

	Typically these are written to a http.Request.
*/
type GetEnterpriseParams struct {

	/* EnterpriseID.

	   The ID of the enterprise to fetch.
	*/
	EnterpriseID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get enterprise params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEnterpriseParams) WithDefaults() *GetEnterpriseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get enterprise params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEnterpriseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get enterprise params
func (o *GetEnterpriseParams) WithTimeout(timeout time.Duration) *GetEnterpriseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get enterprise params
func (o *GetEnterpriseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get enterprise params
func (o *GetEnterpriseParams) WithContext(ctx context.Context) *GetEnterpriseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get enterprise params
func (o *GetEnterpriseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get enterprise params
func (o *GetEnterpriseParams) WithHTTPClient(client *http.Client) *GetEnterpriseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get enterprise params
func (o *GetEnterpriseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnterpriseID adds the enterpriseID to the get enterprise params
func (o *GetEnterpriseParams) WithEnterpriseID(enterpriseID string) *GetEnterpriseParams {
	o.SetEnterpriseID(enterpriseID)
	return o
}

// SetEnterpriseID adds the enterpriseId to the get enterprise params
func (o *GetEnterpriseParams) SetEnterpriseID(enterpriseID string) {
	o.EnterpriseID = enterpriseID
}

// WriteToRequest writes these params to a swagger request
func (o *GetEnterpriseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param enterpriseID
	if err := r.SetPathParam("enterpriseID", o.EnterpriseID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
