// Code generated by go-swagger; DO NOT EDIT.

package enterprises

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListEnterpriseScaleSetsParams creates a new ListEnterpriseScaleSetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListEnterpriseScaleSetsParams() *ListEnterpriseScaleSetsParams {
	return &ListEnterpriseScaleSetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListEnterpriseScaleSetsParamsWithTimeout creates a new ListEnterpriseScaleSetsParams object
// with the ability to set a timeout on a request.
func NewListEnterpriseScaleSetsParamsWithTimeout(timeout time.Duration) *ListEnterpriseScaleSetsParams {
	return &ListEnterpriseScaleSetsParams{
		timeout: timeout,
	}
}

// NewListEnterpriseScaleSetsParamsWithContext creates a new ListEnterpriseScaleSetsParams object
// with the ability to set a context for a request.
func NewListEnterpriseScaleSetsParamsWithContext(ctx context.Context) *ListEnterpriseScaleSetsParams {
	return &ListEnterpriseScaleSetsParams{
		Context: ctx,
	}
}

// NewListEnterpriseScaleSetsParamsWithHTTPClient creates a new ListEnterpriseScaleSetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListEnterpriseScaleSetsParamsWithHTTPClient(client *http.Client) *ListEnterpriseScaleSetsParams {
	return &ListEnterpriseScaleSetsParams{
		HTTPClient: client,
	}
}

/*
ListEnterpriseScaleSetsParams contains all the parameters to send to the API endpoint

	for the list enterprise scale sets operation.

	Typically these are written to a http.Request.
*/
type ListEnterpriseScaleSetsParams struct {

	/* EnterpriseID.

	   Enterprise ID.
	*/
	EnterpriseID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list enterprise scale sets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListEnterpriseScaleSetsParams) WithDefaults() *ListEnterpriseScaleSetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list enterprise scale sets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListEnterpriseScaleSetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list enterprise scale sets params
func (o *ListEnterpriseScaleSetsParams) WithTimeout(timeout time.Duration) *ListEnterpriseScaleSetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list enterprise scale sets params
func (o *ListEnterpriseScaleSetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list enterprise scale sets params
func (o *ListEnterpriseScaleSetsParams) WithContext(ctx context.Context) *ListEnterpriseScaleSetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list enterprise scale sets params
func (o *ListEnterpriseScaleSetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list enterprise scale sets params
func (o *ListEnterpriseScaleSetsParams) WithHTTPClient(client *http.Client) *ListEnterpriseScaleSetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list enterprise scale sets params
func (o *ListEnterpriseScaleSetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnterpriseID adds the enterpriseID to the list enterprise scale sets params
func (o *ListEnterpriseScaleSetsParams) WithEnterpriseID(enterpriseID string) *ListEnterpriseScaleSetsParams {
	o.SetEnterpriseID(enterpriseID)
	return o
}

// SetEnterpriseID adds the enterpriseId to the list enterprise scale sets params
func (o *ListEnterpriseScaleSetsParams) SetEnterpriseID(enterpriseID string) {
	o.EnterpriseID = enterpriseID
}

// WriteToRequest writes these params to a swagger request
func (o *ListEnterpriseScaleSetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param enterpriseID
	if err := r.SetPathParam("enterpriseID", o.EnterpriseID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
