// Code generated by go-swagger; DO NOT EDIT.

package enterprises

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	apiserver_params "github.com/cloudbase/garm/apiserver/params"
	garm_params "github.com/cloudbase/garm/params"
)

// ListEnterprisePoolsReader is a Reader for the ListEnterprisePools structure.
type ListEnterprisePoolsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListEnterprisePoolsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListEnterprisePoolsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListEnterprisePoolsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListEnterprisePoolsOK creates a ListEnterprisePoolsOK with default headers values
func NewListEnterprisePoolsOK() *ListEnterprisePoolsOK {
	return &ListEnterprisePoolsOK{}
}

/*
ListEnterprisePoolsOK describes a response with status code 200, with default header values.

Pools
*/
type ListEnterprisePoolsOK struct {
	Payload garm_params.Pools
}

// IsSuccess returns true when this list enterprise pools o k response has a 2xx status code
func (o *ListEnterprisePoolsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list enterprise pools o k response has a 3xx status code
func (o *ListEnterprisePoolsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list enterprise pools o k response has a 4xx status code
func (o *ListEnterprisePoolsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list enterprise pools o k response has a 5xx status code
func (o *ListEnterprisePoolsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list enterprise pools o k response a status code equal to that given
func (o *ListEnterprisePoolsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list enterprise pools o k response
func (o *ListEnterprisePoolsOK) Code() int {
	return 200
}

func (o *ListEnterprisePoolsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enterprises/{enterpriseID}/pools][%d] listEnterprisePoolsOK %s", 200, payload)
}

func (o *ListEnterprisePoolsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enterprises/{enterpriseID}/pools][%d] listEnterprisePoolsOK %s", 200, payload)
}

func (o *ListEnterprisePoolsOK) GetPayload() garm_params.Pools {
	return o.Payload
}

func (o *ListEnterprisePoolsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListEnterprisePoolsDefault creates a ListEnterprisePoolsDefault with default headers values
func NewListEnterprisePoolsDefault(code int) *ListEnterprisePoolsDefault {
	return &ListEnterprisePoolsDefault{
		_statusCode: code,
	}
}

/*
ListEnterprisePoolsDefault describes a response with status code -1, with default header values.

APIErrorResponse
*/
type ListEnterprisePoolsDefault struct {
	_statusCode int

	Payload apiserver_params.APIErrorResponse
}

// IsSuccess returns true when this list enterprise pools default response has a 2xx status code
func (o *ListEnterprisePoolsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list enterprise pools default response has a 3xx status code
func (o *ListEnterprisePoolsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list enterprise pools default response has a 4xx status code
func (o *ListEnterprisePoolsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list enterprise pools default response has a 5xx status code
func (o *ListEnterprisePoolsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list enterprise pools default response a status code equal to that given
func (o *ListEnterprisePoolsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list enterprise pools default response
func (o *ListEnterprisePoolsDefault) Code() int {
	return o._statusCode
}

func (o *ListEnterprisePoolsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enterprises/{enterpriseID}/pools][%d] ListEnterprisePools default %s", o._statusCode, payload)
}

func (o *ListEnterprisePoolsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /enterprises/{enterpriseID}/pools][%d] ListEnterprisePools default %s", o._statusCode, payload)
}

func (o *ListEnterprisePoolsDefault) GetPayload() apiserver_params.APIErrorResponse {
	return o.Payload
}

func (o *ListEnterprisePoolsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
