// Code generated by go-swagger; DO NOT EDIT.

package enterprises

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListEnterpriseInstancesParams creates a new ListEnterpriseInstancesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListEnterpriseInstancesParams() *ListEnterpriseInstancesParams {
	return &ListEnterpriseInstancesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListEnterpriseInstancesParamsWithTimeout creates a new ListEnterpriseInstancesParams object
// with the ability to set a timeout on a request.
func NewListEnterpriseInstancesParamsWithTimeout(timeout time.Duration) *ListEnterpriseInstancesParams {
	return &ListEnterpriseInstancesParams{
		timeout: timeout,
	}
}

// NewListEnterpriseInstancesParamsWithContext creates a new ListEnterpriseInstancesParams object
// with the ability to set a context for a request.
func NewListEnterpriseInstancesParamsWithContext(ctx context.Context) *ListEnterpriseInstancesParams {
	return &ListEnterpriseInstancesParams{
		Context: ctx,
	}
}

// NewListEnterpriseInstancesParamsWithHTTPClient creates a new ListEnterpriseInstancesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListEnterpriseInstancesParamsWithHTTPClient(client *http.Client) *ListEnterpriseInstancesParams {
	return &ListEnterpriseInstancesParams{
		HTTPClient: client,
	}
}

/*
ListEnterpriseInstancesParams contains all the parameters to send to the API endpoint

	for the list enterprise instances operation.

	Typically these are written to a http.Request.
*/
type ListEnterpriseInstancesParams struct {

	/* EnterpriseID.

	   Enterprise ID.
	*/
	EnterpriseID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list enterprise instances params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListEnterpriseInstancesParams) WithDefaults() *ListEnterpriseInstancesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list enterprise instances params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListEnterpriseInstancesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list enterprise instances params
func (o *ListEnterpriseInstancesParams) WithTimeout(timeout time.Duration) *ListEnterpriseInstancesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list enterprise instances params
func (o *ListEnterpriseInstancesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list enterprise instances params
func (o *ListEnterpriseInstancesParams) WithContext(ctx context.Context) *ListEnterpriseInstancesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list enterprise instances params
func (o *ListEnterpriseInstancesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list enterprise instances params
func (o *ListEnterpriseInstancesParams) WithHTTPClient(client *http.Client) *ListEnterpriseInstancesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list enterprise instances params
func (o *ListEnterpriseInstancesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnterpriseID adds the enterpriseID to the list enterprise instances params
func (o *ListEnterpriseInstancesParams) WithEnterpriseID(enterpriseID string) *ListEnterpriseInstancesParams {
	o.SetEnterpriseID(enterpriseID)
	return o
}

// SetEnterpriseID adds the enterpriseId to the list enterprise instances params
func (o *ListEnterpriseInstancesParams) SetEnterpriseID(enterpriseID string) {
	o.EnterpriseID = enterpriseID
}

// WriteToRequest writes these params to a swagger request
func (o *ListEnterpriseInstancesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param enterpriseID
	if err := r.SetPathParam("enterpriseID", o.EnterpriseID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
