//go:build integration
// +build integration

// Copyright 2025 Cloudbase Solutions SRL
//
//	Licensed under the Apache License, Version 2.0 (the "License"); you may
//	not use this file except in compliance with the License. You may obtain
//	a copy of the License at
//
//	     http://www.apache.org/licenses/LICENSE-2.0
//
//	Unless required by applicable law or agreed to in writing, software
//	distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
//	WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
//	License for the specific language governing permissions and limitations
//	under the License.
package integration

import (
	"context"
	"fmt"
	"slices"
	"time"

	"github.com/google/go-github/v84/github"

	commonParams "github.com/cloudbase/garm-provider-common/params"
	dbCommon "github.com/cloudbase/garm/database/common"
	"github.com/cloudbase/garm/params"
)

func (suite *GarmSuite) TestWorkflowJobs() {
	for _, label := range []string{"org-runner", "repo-runner"} {
		// Mark the event stream before triggering the workflow, so the
		// lifecycle validation only considers events generated by this
		// workflow run.
		since := suite.events.mark()
		suite.TriggerWorkflow(suite.ghToken, orgName, repoName, workflowFileName, label)
		suite.ValidateJobLifecycle(since, label)
	}
}

func (suite *GarmSuite) TriggerWorkflow(ghToken, orgName, repoName, workflowFileName, labelName string) {
	t := suite.T()
	t.Logf("Trigger workflow with label %s", labelName)

	client := getGithubClient(ghToken)
	eventReq := github.CreateWorkflowDispatchEventRequest{
		Ref: "main",
		Inputs: map[string]interface{}{
			"sleep_time":   "50",
			"runner_label": labelName,
		},
	}
	_, _, err := client.Actions.CreateWorkflowDispatchEventByFileName(context.Background(), orgName, repoName, workflowFileName, eventReq)
	suite.NoError(err, "error triggering workflow")
}

// ValidateJobLifecycle follows one workflow job through GARM using the
// database events stream. Every state change GARM records is delivered as
// an event, so unlike polling, fast transitions cannot be missed: an idle
// runner can pick a job up seconds after it was queued, and the queued
// state may never be recorded at all if webhooks arrive out of order.
func (suite *GarmSuite) ValidateJobLifecycle(since int, label string) {
	t := suite.T()
	t.Logf("Validate GARM job lifecycle with label %s", label)

	// Wait for the job to show up in GARM.
	evt, err := suite.events.waitFor(fmt.Sprintf("job with label %s", label), since, 4*time.Minute, func(e dbEvent) bool {
		job, err := e.job()
		if err != nil {
			return false
		}
		return slices.Contains(job.Labels, label)
	})
	suite.Require().NoError(err, "error waiting for job to be recorded")
	job, err := evt.job()
	suite.Require().NoError(err, "error decoding job event")
	workflowJobID := job.WorkflowJobID
	t.Logf("Job %d with label %s recorded with status %s", workflowJobID, label, job.Status)

	// Follow the job to completion, collecting the statuses and the runner
	// name we see along the way. Depending on webhook ordering and timing,
	// the first recorded status may already be in_progress or completed.
	seenStatuses := []string{job.Status}
	runnerName := job.RunnerName
	if params.JobStatus(job.Status) != params.JobStatusCompleted {
		_, err = suite.events.waitFor("job to complete", since, 6*time.Minute, func(e dbEvent) bool {
			j, err := e.job()
			if err != nil || j.WorkflowJobID != workflowJobID {
				return false
			}
			seenStatuses = append(seenStatuses, j.Status)
			if j.RunnerName != "" {
				runnerName = j.RunnerName
			}
			return params.JobStatus(j.Status) == params.JobStatusCompleted
		})
		suite.Require().NoError(err, "error waiting for job to complete")
	}
	t.Logf("Job %d went through statuses %v", workflowJobID, seenStatuses)
	suite.Require().NotEmpty(runnerName, "expected the job to be assigned to a runner")

	// The runner that ran the job is ephemeral. Once the job completes,
	// GARM removes it. The delete event carries the pool ID.
	evt, err = suite.events.waitFor(fmt.Sprintf("runner %s to be removed", runnerName), since, 5*time.Minute, func(e dbEvent) bool {
		instance, err := e.instance()
		if err != nil || e.Operation != dbCommon.DeleteOperation {
			return false
		}
		return instance.Name == runnerName
	})
	suite.Require().NoError(err, "error waiting for runner to be removed")
	instance, err := evt.instance()
	suite.Require().NoError(err, "error decoding instance event")
	suite.Require().NotEmpty(instance.PoolID, "expected the removed runner to belong to a pool")

	// Wait for the pool to rebuild its idle worker.
	_, err = suite.events.waitFor("pool to rebuild an idle worker", since, 5*time.Minute, func(e dbEvent) bool {
		inst, err := e.instance()
		if err != nil || e.Operation == dbCommon.DeleteOperation {
			return false
		}
		return inst.PoolID == instance.PoolID && inst.Name != runnerName &&
			inst.Status == commonParams.InstanceRunning && inst.RunnerStatus == params.RunnerIdle
	})
	suite.Require().NoError(err, "error waiting for pool to rebuild an idle worker")
}
